//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaForm.DNN.Components
{
    public partial class ManageModule
    {
        protected System.Web.UI.WebControls.Panel pnlNoFormsInfo;
        protected System.Web.UI.WebControls.Literal litNoFormsInfo;
        protected System.Web.UI.WebControls.Button btnOpenDashboard;
        protected System.Web.UI.WebControls.Panel pnlFormSelectRow;
        protected DotNetNuke.UI.UserControls.LabelControl lblFormSelect;
        protected System.Web.UI.WebControls.DropDownList ddlForms;
        protected System.Web.UI.WebControls.Panel pnlDefaultViewRow;
        protected DotNetNuke.UI.UserControls.LabelControl lblDefaultView;
        protected System.Web.UI.WebControls.DropDownList ddlDefaultView;
        protected DotNetNuke.UI.UserControls.LabelControl lblRendererHost;
        protected System.Web.UI.WebControls.CheckBox chkUseThisPageAsRendererHost;
        protected System.Web.UI.WebControls.Literal litRendererHostStatus;
        protected System.Web.UI.WebControls.Panel pnlDisplayModeNotApplicable;
        protected System.Web.UI.WebControls.Panel pnlDisplaySettings;
        protected System.Web.UI.WebControls.Panel pnlDisplayModeRow;
        protected DotNetNuke.UI.UserControls.LabelControl lblDisplayMode;
        protected System.Web.UI.WebControls.DropDownList ddlDisplayMode;
        protected System.Web.UI.WebControls.Panel pnlPopupSettings;
        protected System.Web.UI.WebControls.Panel pnlPopupTriggerRow;
        protected DotNetNuke.UI.UserControls.LabelControl lblPopupTrigger;
        protected System.Web.UI.WebControls.DropDownList ddlPopupTrigger;
        protected System.Web.UI.WebControls.Panel pnlDelaySecondsRow;
        protected DotNetNuke.UI.UserControls.LabelControl lblDelaySeconds;
        protected System.Web.UI.WebControls.TextBox txtDelaySeconds;
        protected System.Web.UI.WebControls.Panel pnlScrollPercentRow;
        protected DotNetNuke.UI.UserControls.LabelControl lblScrollPercent;
        protected System.Web.UI.WebControls.TextBox txtScrollPercent;
        protected System.Web.UI.WebControls.Panel pnlClickSelectorRow;
        protected DotNetNuke.UI.UserControls.LabelControl lblClickSelector;
        protected System.Web.UI.WebControls.TextBox txtClickSelector;
        protected System.Web.UI.WebControls.Panel pnlTriggerSampleRow;
        protected DotNetNuke.UI.UserControls.LabelControl lblTriggerSample;
        protected System.Web.UI.WebControls.TextBox txtTriggerSample;
        protected System.Web.UI.WebControls.Panel pnlStartAtRow;
        protected DotNetNuke.UI.UserControls.LabelControl lblStartAt;
        protected System.Web.UI.WebControls.TextBox txtStartAt;
        protected System.Web.UI.WebControls.Panel pnlEndAtRow;
        protected DotNetNuke.UI.UserControls.LabelControl lblEndAt;
        protected System.Web.UI.WebControls.TextBox txtEndAt;
        protected System.Web.UI.WebControls.Panel pnlPopupFlagsRow;
        protected DotNetNuke.UI.UserControls.LabelControl lblPopupFlags;
        protected System.Web.UI.WebControls.CheckBox chkShowOncePerSession;
        protected System.Web.UI.WebControls.CheckBox chkCloseOnOverlay;
        protected System.Web.UI.WebControls.Panel pnlAutoQrCodeRow;
        protected DotNetNuke.UI.UserControls.LabelControl lblAutoQrCode;
        protected System.Web.UI.WebControls.CheckBox chkEnableAutoQrCode;
        protected System.Web.UI.WebControls.Button btnUpdate;
        protected System.Web.UI.WebControls.Button btnGoToDashboard;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.Label lblMessage;
    }
}
