//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaForm.DNN.Components
{
    public partial class FormSettings
    {
        protected DotNetNuke.UI.UserControls.LabelControl lblFormSelect;
        protected System.Web.UI.WebControls.DropDownList ddlForms;
        protected DotNetNuke.UI.UserControls.LabelControl lblDefaultView;
        protected System.Web.UI.WebControls.DropDownList ddlDefaultView;
        protected DotNetNuke.UI.UserControls.LabelControl lblCustomView;
        protected System.Web.UI.WebControls.DropDownList ddlCustomView;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divCustomViews;
        protected DotNetNuke.UI.UserControls.LabelControl lblAppScope;
        protected System.Web.UI.WebControls.DropDownList ddlAppScope;
        protected System.Web.UI.WebControls.TextBox txtNewScope;
        protected DotNetNuke.UI.UserControls.LabelControl lblBusChannel;
        protected System.Web.UI.WebControls.TextBox txtBusChannel;
        protected DotNetNuke.UI.UserControls.LabelControl lblDetailModuleId;
        protected System.Web.UI.WebControls.TextBox txtDetailModuleId;
        protected DotNetNuke.UI.UserControls.LabelControl lblCreateNew;
        protected System.Web.UI.WebControls.HyperLink lnkCreateNew;
    }
}
