//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaForm.DNN.Components
{
    public partial class SubmissionsView
    {
        // No server controls declared in Submissions.ascx that need designer references.
        // All UI is rendered via inline expressions and client-side JavaScript.
    }
}
