# ============================================================
#  MegaForm.DNN - DNN Install Package Creator
#
#  Tao file Install ZIP cai dat qua DNN Host > Extensions.
#  Chay: powershell -ExecutionPolicy Bypass -File BuildPackage-DNN.ps1
#
#  Mac dinh script nay co the tu build TypeScript + dotnet build
#  truoc khi package khi duoc goi tu BuildPackage-DNN.bat.
# ============================================================

[CmdletBinding()]
param(
    [switch]$BuildTS,
    [switch]$BuildDotNet,
    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Release',
    # [LicenseEdition 2026-07-24] -Trial builds the TRIAL edition: the license.lic marker is
    # OMITTED from the package, so a fresh install runs unlicensed (form/submission caps + AI
    # lock apply). Without -Trial the PRODUCTION edition ships license.lic="production" (unlimited).
    # The two editions are otherwise byte-identical. Zip name gets a _Trial suffix so the artifacts
    # never collide.
    [switch]$Trial,
    # [GalleryRepo 2026-07-24] Premium templates + their artwork are published to the
    # gallery repo and downloaded on demand, so NEITHER edition ships them. Trial has no
    # premium templates at all and cannot reach the gallery (402) — that is the product
    # model: the premium set is part of what a license buys.
    # Pass -KeepGalleryContent to build a self-contained package anyway.
    [switch]$KeepGalleryContent,
    [switch]$NoPause
)

$ErrorActionPreference = 'Stop'
$MODULE_NAME  = 'MegaForm'
$PROJECT_DIR  = Split-Path -Parent $MyInvocation.MyCommand.Path
$SOLUTION_DIR = Split-Path -Parent $PROJECT_DIR

# [DNN version single-source 2026-07-18] Derive the package version from the manifest so the
# build script and MegaForm.dnn can NEVER drift. They HAD drifted: this script hard-coded
# 01.07.106 while MegaForm.dnn declares 01.07.108, so the generated zip name lied about its
# version and shipped an install artifact built before 01.06.39.SqlDataProvider existed.
$MANIFEST     = Join-Path $PROJECT_DIR 'MegaForm.dnn'
$verMatch     = Select-String -Path $MANIFEST -Pattern '<package name="MegaForm"[^>]*version="([0-9.]+)"'
if (-not $verMatch) { throw "Khong doc duoc <package version> tu MegaForm.dnn" }
$VERSION      = $verMatch.Matches[0].Groups[1].Value
$STAGING      = Join-Path $PROJECT_DIR '_package'
$RESOURCES    = Join-Path $STAGING '_resources'
$OUTPUT_DIR   = Join-Path $PROJECT_DIR 'Install'
$EDITION      = if ($Trial) { 'Trial' } else { 'Production' }

# ── gallery-hosted content (generated by tools/gallery/build-gallery.mjs) ──
# Reading the generated list (never a hard-coded one) keeps the package exactly in
# sync with what the gallery actually serves: publish a new template and both update.
$SLIM_GALLERY = -not $KeepGalleryContent
$GALLERY_TPL  = @()
$GALLERY_IMG  = @()
$GALLERY_KEEP = @()
if ($SLIM_GALLERY) {
    $exclPath = Join-Path $SOLUTION_DIR 'tools\gallery\gallery-exclude.json'
    if (Test-Path $exclPath) {
        try {
            $excl = Get-Content $exclPath -Raw | ConvertFrom-Json
            $GALLERY_TPL = @($excl.templateFiles)
            $GALLERY_IMG = @($excl.images)
            # Allow-LIST, not deny-list: copy exactly the named bundled starters. A deny-list
            # ("anything not gallery-hosted") also ships whatever the publisher REFUSED —
            # which is how DNN ended up with 8 premium starters against Oqtane's 4.
            $GALLERY_KEEP = @($excl.bundledFiles)
        } catch {
            throw "gallery-exclude.json is unreadable: $($_.Exception.Message). Re-run tools/gallery/build-gallery.mjs."
        }
    } else {
        # Fail loudly: silently shipping the full package would hide the regression.
        throw "SLIM build requested but tools/gallery/gallery-exclude.json is missing. Run: node tools/gallery/build-gallery.mjs --out <gallery-repo>"
    }
}
$EDITION_TAG  = if ($Trial) { '_Trial' } else { '' }
$OUTPUT_ZIP   = Join-Path $OUTPUT_DIR "${MODULE_NAME}_${VERSION}${EDITION_TAG}_Install.zip"
$ROOT_BUILDTS_BAT = Join-Path $SOLUTION_DIR 'BuildTS.bat'
$DNN_CSPROJ       = Join-Path $PROJECT_DIR 'MegaForm.DNN.csproj'

# [PkgSlim 2026-07-28] Source maps are build artifacts: ~0.22 MB of the package, downloaded by
# nobody at runtime and useful only with the original sources, which do not ship either.
function Test-BuildArtifact {
    param([Parameter(Mandatory = $true)][string]$FileName)
    return $FileName -like '*.map'
}

# [CodeEditorAddOn 2026-07-28] The Monaco bundle behind the Source/Razor tab — 1.02 MB, the single
# biggest file in the package, and only builder users who open a code editor ever load it. It ships
# as its own add-on. Safe to leave out: the builder injects it with a <script> tag whose onerror
# path is already handled, and mountMonacoEditor() falls back to a plain <textarea> with the same
# contract (written for air-gapped installs).
$CODE_EDITOR_JS = 'megaform-unified-monaco.js'

# [PkgSlim 2026-07-28] Artwork for templates that no longer exist anywhere in the package.
# festa-italiana was removed from the gallery, so its two 1024x1024 PNGs (2.6 MB) are referenced
# by nothing that ships — the one mention left in the dashboard image picker points at
# img/mock/festa-italiana-hero.png, a path this package does not carry at all.
$ORPHAN_IMG = @(
    'festa-italiana/festa-italiana-hero.png',
    'festa-italiana/festa-italiana-texture.png'
)

function Assert-CommandAvailable {
    param(
        [Parameter(Mandatory = $true)][string]$CommandName,
        [Parameter(Mandatory = $true)][string]$FriendlyName
    )
    if (-not (Get-Command $CommandName -ErrorAction SilentlyContinue)) {
        throw "$FriendlyName khong tim thay trong PATH."
    }
}

function Assert-RequiredFile {
    param(
        [Parameter(Mandatory = $true)][string]$PathToCheck,
        [Parameter(Mandatory = $true)][string]$Label
    )
    if (-not (Test-Path $PathToCheck)) {
        throw "Thieu file bat buoc: $Label -> $PathToCheck"
    }
    Write-Host "  [OK] $Label" -ForegroundColor Green
}

function Invoke-Step {
    param(
        [Parameter(Mandatory = $true)][string]$Title,
        [Parameter(Mandatory = $true)][scriptblock]$Action
    )
    Write-Host $Title -ForegroundColor Yellow
    & $Action
    Write-Host ''
}

Write-Host ''
Write-Host '============================================================' -ForegroundColor Cyan
Write-Host "  $MODULE_NAME - DNN Install Package v$VERSION" -ForegroundColor Cyan
Write-Host '============================================================' -ForegroundColor Cyan
Write-Host ''

# ============================================================
#  0. Pre-build (optional but enabled by BuildPackage-DNN.bat)
# ============================================================
if ($BuildTS) {
    Invoke-Step '[0/7] Build TypeScript bundles...' {
        Assert-CommandAvailable -CommandName 'powershell' -FriendlyName 'PowerShell'
        if (-not (Test-Path $ROOT_BUILDTS_BAT)) {
            throw "Khong tim thay BuildTS.bat tai root solution: $ROOT_BUILDTS_BAT"
        }
        & $ROOT_BUILDTS_BAT
        if ($LASTEXITCODE -ne 0) {
            throw "BuildTS.bat that bai voi ma loi $LASTEXITCODE"
        }
    }
}

if ($BuildDotNet) {
    Invoke-Step "[0b/7] Build MegaForm.DNN ($Configuration)..." {
        Assert-CommandAvailable -CommandName 'dotnet' -FriendlyName '.NET SDK'
        if (-not (Test-Path $DNN_CSPROJ)) {
            throw "Khong tim thay csproj: $DNN_CSPROJ"
        }
        dotnet build $DNN_CSPROJ -c $Configuration
        if ($LASTEXITCODE -ne 0) {
            throw "dotnet build MegaForm.DNN that bai voi ma loi $LASTEXITCODE"
        }
    }
}

# ============================================================
#  1. Tim DLL
# ============================================================
Write-Host '[1/7] Tim DLLs...' -ForegroundColor Yellow

$dnnDllPaths = @(
    "$PROJECT_DIR\bin\$Configuration\net472\MegaForm.DNN.dll",
    "$PROJECT_DIR\bin\$Configuration\MegaForm.DNN.dll",
    "$PROJECT_DIR\bin\Release\net472\MegaForm.DNN.dll",
    "$PROJECT_DIR\bin\Debug\net472\MegaForm.DNN.dll",
    "$PROJECT_DIR\bin\Release\MegaForm.DNN.dll",
    "$PROJECT_DIR\bin\Debug\MegaForm.DNN.dll"
)
$dnnDll = $null
foreach ($p in $dnnDllPaths) {
    if (Test-Path $p) { $dnnDll = $p; break }
}
if (-not $dnnDll) {
    throw 'MegaForm.DNN.dll khong tim thay! Hay build truoc: dotnet build -c Release'
}
Write-Host "  MegaForm.DNN.dll: $dnnDll" -ForegroundColor Green

$coreDll = Join-Path (Split-Path $dnnDll) 'MegaForm.Core.dll'
if (-not (Test-Path $coreDll)) {
    $coreDll = @(
        "$SOLUTION_DIR\MegaForm.Core\bin\$Configuration\net472\MegaForm.Core.dll",
        "$SOLUTION_DIR\MegaForm.Core\bin\Release\net472\MegaForm.Core.dll",
        "$SOLUTION_DIR\MegaForm.Core\bin\Debug\net472\MegaForm.Core.dll"
    ) | Where-Object { Test-Path $_ } | Select-Object -First 1
}
if (-not $coreDll -or -not (Test-Path $coreDll)) {
    throw 'MegaForm.Core.dll khong tim thay! Build Core/DNN truoc khi package.'
}
Write-Host "  MegaForm.Core.dll: $coreDll" -ForegroundColor Green

# [2026-06-23] MegaForm.Sdk.dll — DnnServiceLocator..ctor() loads it; omitting it from
# the package broke FormsOverview / Reports / scheduler tasks at runtime. Bundle it.
$sdkDll = Join-Path (Split-Path $dnnDll) 'MegaForm.Sdk.dll'
if (-not (Test-Path $sdkDll)) {
    $sdkDll = @(
        "$SOLUTION_DIR\MegaForm.Sdk\bin\$Configuration\net472\MegaForm.Sdk.dll",
        "$SOLUTION_DIR\MegaForm.Sdk\bin\Release\net472\MegaForm.Sdk.dll",
        "$SOLUTION_DIR\MegaForm.Sdk\bin\Debug\net472\MegaForm.Sdk.dll"
    ) | Where-Object { Test-Path $_ } | Select-Object -First 1
}
if (-not $sdkDll -or -not (Test-Path $sdkDll)) {
    throw 'MegaForm.Sdk.dll khong tim thay! Build Sdk/Core/DNN truoc khi package.'
}
Write-Host "  MegaForm.Sdk.dll: $sdkDll" -ForegroundColor Green

$dapperDll = Join-Path (Split-Path $dnnDll) 'Dapper.dll'
Write-Host ''

# ============================================================
#  2. Don dep + tao thu muc
# ============================================================
Write-Host '[2/7] Chuan bi thu muc...' -ForegroundColor Yellow

if (Test-Path $STAGING) { Remove-Item $STAGING -Recurse -Force }

@(
    $STAGING, "$STAGING\bin", "$STAGING\SqlScripts",
    "$RESOURCES\Views",
    "$RESOURCES\Assets\css", "$RESOURCES\Assets\css\plugins",
    "$RESOURCES\Assets\js", "$RESOURCES\Assets\js\builder",
    "$RESOURCES\Assets\js\bundles",
    "$RESOURCES\Assets\js\plugins", "$RESOURCES\Assets\js\locales",
    "$RESOURCES\Assets\Images", "$RESOURCES\Samples",
    "$RESOURCES\Images",
    $OUTPUT_DIR
) | ForEach-Object {
    if (-not (Test-Path $_)) { New-Item -ItemType Directory -Path $_ -Force | Out-Null }
}

# ============================================================
#  2b. TypeScript bundles / workflow assets verification
# ============================================================
$bundlesDir = Join-Path $SOLUTION_DIR 'Assets\js\bundles'
$builderDir = Join-Path $SOLUTION_DIR 'Assets\js\builder'
if (-not (Test-Path $bundlesDir)) {
    throw "Assets\js\bundles\ khong tim thay - can chay BuildTS.bat truoc khi package."
}
$bundleCount = (Get-ChildItem "$bundlesDir\*.js" -ErrorAction SilentlyContinue).Count
Write-Host "[2b] Found $bundleCount TS bundles in Assets\js\bundles\" -ForegroundColor Green
Assert-RequiredFile -PathToCheck (Join-Path $bundlesDir 'megaform-builder.js') -Label 'Builder bundle'
Assert-RequiredFile -PathToCheck (Join-Path $SOLUTION_DIR 'Assets\js\megaform-builder-loader.js') -Label 'Builder loader'
Assert-RequiredFile -PathToCheck (Join-Path $SOLUTION_DIR 'Assets\js\plugins\megaform-widget-qrcode.js') -Label 'QRCode plugin'
Assert-RequiredFile -PathToCheck (Join-Path $SOLUTION_DIR 'Assets\js\plugins\megaform-widget-rich-text.js') -Label 'RichText widget'
Assert-RequiredFile -PathToCheck (Join-Path $SOLUTION_DIR 'Assets\js\plugins\vendor\quill\quill.min.js') -Label 'Self-hosted Quill runtime'
Assert-RequiredFile -PathToCheck (Join-Path $SOLUTION_DIR 'Assets\css\plugins\vendor\quill\quill.snow.css') -Label 'Self-hosted Quill theme'
Assert-RequiredFile -PathToCheck (Join-Path $SOLUTION_DIR 'Assets\js\megaform-dashboard.js') -Label 'Dashboard bundle'
Assert-RequiredFile -PathToCheck (Join-Path $builderDir 'megaform-workflow-reactflow.js') -Label 'Workflow canvas bundle'
Assert-RequiredFile -PathToCheck (Join-Path $builderDir 'react.production.min.js') -Label 'React runtime'
Assert-RequiredFile -PathToCheck (Join-Path $builderDir 'react-dom.production.min.js') -Label 'ReactDOM runtime'
Assert-RequiredFile -PathToCheck (Join-Path $builderDir 'reactflow.min.js') -Label 'ReactFlow runtime'
Assert-RequiredFile -PathToCheck (Join-Path $builderDir 'reactflow.min.css') -Label 'ReactFlow CSS'
Write-Host ''

# ============================================================
#  3. Copy files
# ============================================================
Write-Host '[3/7] Copy files...' -ForegroundColor Yellow

Copy-Item "$PROJECT_DIR\MegaForm.dnn" "$STAGING\" -Force
Write-Host '  + MegaForm.dnn'

# [AzureResidue 2026-08-11] <component type="Cleanup" fileName="..."> names a file that has to sit
# at the package ROOT. When it is absent DNN skips the cleanup SILENTLY — the install still reports
# success while the stale Azure DLLs stay in bin and keep the Control Bar returning 500, which is
# the worst possible failure mode for a fix whose whole job is deleting them. Read the name out of
# the manifest instead of hard-coding it (same single-source rule as $VERSION and the SQL scripts)
# and fail the build when the list file is missing.
$cleanupNames = ([regex]::Matches((Get-Content $MANIFEST -Raw), '<component\s+type="Cleanup"[^>]*\bfileName="([^"]+)"') |
    ForEach-Object { $_.Groups[1].Value }) | Sort-Object -Unique
foreach ($cleanupName in $cleanupNames) {
    $cleanupSrc = Join-Path "$PROJECT_DIR\Cleanup" $cleanupName
    if (-not (Test-Path $cleanupSrc)) {
        throw ('MegaForm.dnn declares <component type="Cleanup" fileName="{0}"> but Cleanup\{0} does not exist.' -f $cleanupName)
    }
    Copy-Item $cleanupSrc "$STAGING\" -Force
    Write-Host "  + $cleanupName (danh sach file can xoa khoi bin)"
}

# [DNN sync 2026-06-22] icon.gif is declared in the manifest's <component type="File"> at the
# package root but was never copied/zipped — add it so the install matches the manifest.
$iconSrc = @("$PROJECT_DIR\Images\icon.gif", "$PROJECT_DIR\Install\icon.gif", "$PROJECT_DIR\icon.gif") |
    Where-Object { Test-Path $_ } | Select-Object -First 1
if ($iconSrc) {
    Copy-Item $iconSrc "$STAGING\icon.gif" -Force
    Write-Host '  + icon.gif'
}

# [ModuleIcon v20260716-01] The manifest's <iconFile> points at
# ~/DesktopModules/MegaForm/Images/module-icon.png, and the DB Packages.IconFile row matches —
# but the Images folder was never shipped in Resources.zip, so installed sites 404 the icon and
# the Add-Module list shows MegaForm without one (owner report). Ship the module Images folder.
foreach ($img in @("$PROJECT_DIR\Images\module-icon.png", "$PROJECT_DIR\Images\icon.gif")) {
    if (Test-Path $img) {
        Copy-Item $img "$RESOURCES\Images\" -Force
        Write-Host ('  + Images\' + (Split-Path $img -Leaf))
    }
}

if (Test-Path "$PROJECT_DIR\License.txt") {
    Copy-Item "$PROJECT_DIR\License.txt" "$STAGING\" -Force
} else {
    "MegaForm Module for DNN`r`nCopyright (c) 2025. All rights reserved.`r`nMIT License" | Out-File "$STAGING\License.txt" -Encoding UTF8
}

if (Test-Path "$PROJECT_DIR\ReleaseNotes.txt") {
    Copy-Item "$PROJECT_DIR\ReleaseNotes.txt" "$STAGING\" -Force
} else {
    $releaseNotes = @'
<h3>MegaForm v1.5.0</h3>
<ul>
  <li>Architecture: Split into MegaForm.Core + MegaForm.DNN</li>
  <li>Row/Column layout support in builder and public view</li>
  <li>Workflows, Permissions, Views, Templates (Phase 2)</li>
  <li>Webhook with HMAC-SHA256 signatures</li>
  <li>Anti-spam: honeypot + rate limit + heuristic scoring</li>
  <li>Save and Continue with resume tokens</li>
  <li>18+ field types, drag-and-drop builder</li>
  <li>TypeScript UI bundles for cross-platform support</li>
</ul>
'@
    $releaseNotes | Out-File "$STAGING\ReleaseNotes.txt" -Encoding UTF8
}

Copy-Item $dnnDll "$STAGING\bin\" -Force
Write-Host '  + bin\MegaForm.DNN.dll'
Copy-Item $coreDll "$STAGING\bin\" -Force
Write-Host '  + bin\MegaForm.Core.dll'
Copy-Item $sdkDll "$STAGING\bin\" -Force
Write-Host '  + bin\MegaForm.Sdk.dll'

# [PersonaBarMerge 2026-08-01] Content > MegaForm panel, folded in from the former
# MegaForm.PersonaBar package. Built separately because it targets net48 (Dnn.PersonaBar.Library
# on DNN 10.x is a 4.8 assembly and a net472 project cannot reference it at all).
$pbDll = @(
    "$SOLUTION_DIR\MegaForm.PersonaBar\bin\$Configuration\net48\MegaForm.PersonaBar.dll",
    "$SOLUTION_DIR\MegaForm.PersonaBar\bin\Release\net48\MegaForm.PersonaBar.dll",
    "$SOLUTION_DIR\MegaForm.PersonaBar\bin\Debug\net48\MegaForm.PersonaBar.dll"
) | Where-Object { Test-Path $_ } | Select-Object -First 1

if ($pbDll) {
    Copy-Item $pbDll "$STAGING\bin\" -Force
    Write-Host '  + bin\MegaForm.PersonaBar.dll'
} else {
    # Not fatal, but the package would install a menu whose controller does not exist, so say so
    # loudly rather than shipping a panel whose every API call 404s.
    Write-Warning 'MegaForm.PersonaBar.dll khong tim thay - panel Content > MegaForm se KHONG chay.'
    Write-Warning '  Build truoc: dotnet build MegaForm.PersonaBar\MegaForm.PersonaBar.csproj -c Release'
}
if ($dapperDll -and (Test-Path $dapperDll)) {
    Copy-Item $dapperDll "$STAGING\bin\" -Force
    Write-Host '  + bin\Dapper.dll'
}

# [ScriptingBundled 2026-08-14] The after-submit C# script engine, bundled into the module package
# on the owner's call (+12 MB). Until now MegaForm.Scripting shipped in NO package at all: the
# capability was built, tested and documented, but every site installed from the zip took the
# fail-closed branch in AfterSubmitScriptService.Run — "Script compiler is not installed on this
# server" — and the feature had only ever run where the DLLs were hand-copied.
#
# SHIP EXACTLY THESE FOUR. The net472 build output is 18 MB across 17 assemblies, but DNN 10.3
# already carries ten of them (System.Collections.Immutable, System.Memory, System.Buffers,
# System.Numerics.Vectors, System.Runtime.CompilerServices.Unsafe, System.Threading.Tasks.Extensions,
# System.ValueTuple, System.Text.Encoding.CodePages, System.Text.Json, Newtonsoft.Json) at NEWER
# versions than Roslyn 4.10 was built against. Shipping our older copies over DNN's would be the
# same mistake as the Azure chain above: DNN scans every bin assembly at startup, and a downgraded
# framework assembly is exactly how a site loses its Control Bar for the life of the app domain.
# The three Roslyn pieces below are genuinely absent from a stock DNN bin - verified against
# megaclean008 (DNN 10.3.0) before choosing this set.
$scriptingSrcDir = @(
    "$SOLUTION_DIR\MegaForm.Scripting\bin\$Configuration\net472",
    "$SOLUTION_DIR\MegaForm.Scripting\bin\Release\net472",
    "$SOLUTION_DIR\MegaForm.Scripting\bin\Debug\net472"
) | Where-Object { Test-Path (Join-Path $_ 'MegaForm.Scripting.dll') } | Select-Object -First 1

$scriptingDlls = @('MegaForm.Scripting.dll', 'Microsoft.CodeAnalysis.dll',
                   'Microsoft.CodeAnalysis.CSharp.dll', 'System.Reflection.Metadata.dll')
if ($scriptingSrcDir) {
    $scriptingBytes = 0
    foreach ($name in $scriptingDlls) {
        $src = Join-Path $scriptingSrcDir $name
        if (Test-Path $src) {
            Copy-Item $src "$STAGING\bin\" -Force
            $scriptingBytes += (Get-Item $src).Length
        } else {
            Write-Warning ("Scripting: thieu {0} trong {1}" -f $name, $scriptingSrcDir)
        }
    }
    Write-Host ('  + bin\ scripting engine: {0} DLL, {1:N1} MB' -f $scriptingDlls.Count, ($scriptingBytes / 1MB))
} else {
    # Not fatal here - the manifest/zip parity check at the end of this script is what actually
    # stops a package that declares these and does not carry them.
    Write-Warning 'MegaForm.Scripting net472 khong tim thay - tinh nang After-Submit C# Script se KHONG cai duoc.'
    Write-Warning '  Build truoc: dotnet build MegaForm.Scripting\MegaForm.Scripting.csproj -c Release -f net472'
}

# [CloudStorage v20260723-01] Cloud storage provider DLLs (Google Drive rides on the framework
# HttpClient; Amazon S3 ships its SDK). Copied from the DNN build output (they flow there via the
# MegaForm.Integrations.CloudStorage project reference).
# [AzureBlobRemoved v20260726] Azure Blob provider was DROPPED. Azure.Storage.Blobs pulled Azure.Core
# 1.55 → System.ClientModel + .NET 10 System.* transitively; Azure.Core carries an assembly-level
# attribute whose type lives in System.ClientModel, and DNN scans EVERY bin assembly's custom
# attributes at startup (MEF SafeDirectoryCatalog) → a missing System.ClientModel.dll took the WHOLE
# DNN site down (TypeInitializationException 'ExtensionPointManager'). Removing the Azure Blob
# provider deletes that entire fragile dependency chain — no Azure.Core / Azure.Storage.* /
# System.ClientModel / System.Memory.Data / System.IO.Hashing / System.Diagnostics.DiagnosticSource
# ship anymore, and the net472 build/package is clean. Only the S3 SDK is bundled.
# [S3AddOn 2026-07-28] These three DLLs are NO LONGER in the module package. AWSSDK.Core +
# AWSSDK.S3 are 0.72 MB that only an S3-mirroring install ever executes, and the package has to
# fit the store's upload limit. They ship as a separate add-on zip built at the end of this
# script; DnnServiceLocator resolves the provider by reflection and simply offers one less cloud
# target when the add-on is absent.
$cloudDllNames = @(
    'MegaForm.Integrations.CloudStorage.dll',
    'AWSSDK.Core.dll',
    'AWSSDK.S3.dll'
)

# [DNN sync 2026-06-22] DNN scripts are *.SqlDataProvider (not *.sql); the old `*.sql` glob copied
# ZERO scripts so installs/upgrades shipped no schema. Copy both extensions.
# [PkgSlim 2026-07-29] …but ONLY .SqlDataProvider actually runs. DNN executes the scripts NAMED in
# the manifest's <component type="Script"> block, and every one of those 36 nodes names a
# *.SqlDataProvider file — not a single plain .sql is declared. The 14 plain .sql files (the
# 01.06.28*-seed.sql set, 160 KB compressed) therefore shipped to every customer and were never
# executed by anything. Package the declared extension only.
# [SqlMerge 2026-08-14] Those 14 .sql files have since been deleted from SqlScripts\ outright, and
# the 40 per-version .SqlDataProvider scripts were merged into two. The folder now contains only
# what DNN runs: 01.06.42, 02.00.018, Uninstall. Keep the -Include filter anyway - it is what stops
# a stray .sql from silently rejoining the package.
Get-ChildItem "$PROJECT_DIR\SqlScripts\*" -Include *.SqlDataProvider -ErrorAction SilentlyContinue | ForEach-Object {
    Copy-Item $_.FullName "$STAGING\SqlScripts\" -Force
    Write-Host "  + SqlScripts\$($_.Name)"
}

# Every script the manifest declares must be on disk, or the install runs against a half-built
# schema. Fail the build loudly instead of shipping the gap.
$declaredScripts = ([regex]::Matches((Get-Content $MANIFEST -Raw), '<name>([^<]+\.SqlDataProvider)</name>') |
    ForEach-Object { $_.Groups[1].Value }) | Sort-Object -Unique
$missingScripts = @($declaredScripts | Where-Object { -not (Test-Path (Join-Path "$STAGING\SqlScripts" $_)) })
if ($missingScripts.Count -gt 0) {
    throw ("MegaForm.dnn declares {0} SQL script(s) that are not in SqlScripts\: {1}" -f $missingScripts.Count, ($missingScripts -join ', '))
}
Write-Host ("  [OK] {0} manifest-declared SQL script(s) present" -f $declaredScripts.Count) -ForegroundColor Green

# [PkgSlim 2026-07-29] Views\*Old.ascx (FormViewOld, FormEditOld) are registered by NO manifest —
# not the current one, not any that ever shipped — and MegaForm.DNN.csproj already excludes their
# code-behind. A blanket glob is what kept shipping them. Package what the manifest registers.
$registeredViews = ([regex]::Matches((Get-Content $MANIFEST -Raw), '<controlSrc>[^<]*/([^/<]+\.ascx)</controlSrc>') |
    ForEach-Object { $_.Groups[1].Value }) | Sort-Object -Unique
foreach ($view in $registeredViews) {
    $src = Join-Path "$PROJECT_DIR\Views" $view
    if (-not (Test-Path $src)) { throw "MegaForm.dnn registers Views\$view but the file is missing." }
    Copy-Item $src "$RESOURCES\Views\" -Force
    Write-Host "  + Views\$view"
}
# The builder/editor markup the registered controls pull in at runtime is not itself a moduleControl.
foreach ($extraView in @('FormEdit.ascx', 'Submissions.ascx')) {
    $src = Join-Path "$PROJECT_DIR\Views" $extraView
    if ((Test-Path $src) -and -not (Test-Path (Join-Path "$RESOURCES\Views" $extraView))) {
        Copy-Item $src "$RESOURCES\Views\" -Force
        Write-Host "  + Views\$extraView"
    }
}

$assetsDir = "$SOLUTION_DIR\Assets"
if (-not (Test-Path $assetsDir)) {
    $assetsDir = "$PROJECT_DIR\Assets"
}
if (-not (Test-Path $assetsDir)) {
    throw 'Assets\ khong tim thay!'
}

Get-ChildItem "$assetsDir\css\*.css" -ErrorAction SilentlyContinue | ForEach-Object {
    Copy-Item $_.FullName "$RESOURCES\Assets\css\" -Force
    Write-Host "  + Assets\css\$($_.Name)"
}
if (Test-Path "$assetsDir\css\plugins") {
    Get-ChildItem "$assetsDir\css\plugins\*" -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
        $rel = $_.FullName.Replace("$assetsDir\css\plugins\", '')
        $destDir = Join-Path "$RESOURCES\Assets\css\plugins" (Split-Path $rel)
        if (-not (Test-Path $destDir)) { New-Item -ItemType Directory -Path $destDir -Force | Out-Null }
        Copy-Item $_.FullName (Join-Path "$RESOURCES\Assets\css\plugins" $rel) -Force
    }
    Write-Host '  + Assets\css\plugins\*'
}

Get-ChildItem "$assetsDir\js\*.js" -ErrorAction SilentlyContinue | ForEach-Object {
    if (Test-BuildArtifact $_.Name) { return }
    # [CodeEditorAddOn 2026-07-28] Monaco (1.02 MB, 15% of the package) ships separately.
    if ($_.Name -eq $CODE_EDITOR_JS) { return }
    Copy-Item $_.FullName "$RESOURCES\Assets\js\" -Force
    Write-Host "  + Assets\js\$($_.Name)"
}

if (Test-Path "$assetsDir\js\builder") {
    Get-ChildItem "$assetsDir\js\builder\*" -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
        $rel = $_.FullName.Replace("$assetsDir\js\builder\", '')
        # [LanguagePacksAddOn 2026-07-29] builder\i18n is handled by its own explicit step below,
        # which keeps the default pair and hands the rest to the add-on. This recursive copy would
        # otherwise put all 39 back — the same way the plugins copy used to smuggle in a 4th set.
        if ($rel -like 'i18n\*') { return }
        if (Test-BuildArtifact $_.Name) { return }
        $destDir = Join-Path "$RESOURCES\Assets\js\builder" (Split-Path $rel)
        if (-not (Test-Path $destDir)) { New-Item -ItemType Directory -Path $destDir -Force | Out-Null }
        Copy-Item $_.FullName (Join-Path "$RESOURCES\Assets\js\builder" $rel) -Force
        Write-Host "  + Assets\js\builder\$rel" -ForegroundColor Cyan
    }
}

if (Test-Path "$assetsDir\js\bundles") {
    Get-ChildItem "$assetsDir\js\bundles\*" -File -ErrorAction SilentlyContinue | ForEach-Object {
        if (Test-BuildArtifact $_.Name) { return }
        Copy-Item $_.FullName "$RESOURCES\Assets\js\bundles\" -Force
        Write-Host "  + Assets\js\bundles\$($_.Name)" -ForegroundColor Magenta
    }
}

if (Test-Path "$assetsDir\js\plugins") {
    Get-ChildItem "$assetsDir\js\plugins\*" -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
        $rel = $_.FullName.Replace("$assetsDir\js\plugins\", '')
        # [PkgSlim 2026-07-28] plugins\i18n is a 4th identical copy of the 39 locale files —
        # nothing resolves locales relative to the plugins folder (see the i18n note below).
        if ($rel -like 'i18n\*') { return }
        if (Test-BuildArtifact $_.Name) { return }
        $destDir = Join-Path "$RESOURCES\Assets\js\plugins" (Split-Path $rel)
        if (-not (Test-Path $destDir)) { New-Item -ItemType Directory -Path $destDir -Force | Out-Null }
        Copy-Item $_.FullName (Join-Path "$RESOURCES\Assets\js\plugins" $rel) -Force
    }
    Write-Host '  + Assets\js\plugins\*'
}

if (Test-Path "$assetsDir\js\locales") {
    Get-ChildItem "$assetsDir\js\locales\*" -File -ErrorAction SilentlyContinue | ForEach-Object {
        Copy-Item $_.FullName "$RESOURCES\Assets\js\locales\" -Force
    }
    Write-Host '  + Assets\js\locales\*'
}

# [i18n language packs 2026-07-09] EXPLICIT + ROBUST copy of the 39 locale JSON files
# (+ index.json). These feed BOTH the Languages admin panel (MegaFormApiController.List
# enumerates these folders) AND runtime lazy-loading of non-English locales.
# [PkgSlim 2026-07-28] ONE folder, not three. The same 39 files rode in four times
# (js\i18n, js\builder\i18n, js\bundles\i18n and — via the recursive plugins copy —
# js\plugins\i18n): 4.15 MB shipped for 1.04 MB of content, the single biggest waste in the
# package. builder\i18n is the copy both readers actually use: the browser resolves
# /DesktopModules/MegaForm/Assets/js/builder/i18n/<loc>.json (resolveI18nBase in
# MegaForm.UI/src/i18n/index.ts) and the API probe list ResolveI18nFolders() includes it —
# it returns the FIRST folder that exists, and ResolveWritableI18nFolder (the Languages panel's
# save target) points at builder\i18n too.
# [LanguagePacksAddOn 2026-07-29] 39 locale files were 1.06 MB of a 6 MB package — the single
# biggest block in it. Only the ones a site actually renders are needed on disk: loadLocale()
# fetches ONE locale by name (megaform-i18n.js), so the rest were bytes every customer downloaded
# and no install ever read. Ship the default pair + the manifest, move the other 36 into the
# MegaForm.LanguagePacks add-on. Deliberately an ADD-ON, not a CDN fetch: on a public form the
# request is an anonymous browser GET of a static file, so a remote base would send every
# non-English visitor to a third-party host and break air-gapped/intranet DNN installs outright.
# [LocaleSwap 2026-08-13] The bundled pair used to be en-US + vi-VN. vi-VN left the product, and
# the six languages the owner requires in the shipped package (Dutch, Urdu, Spanish, British
# English, French, Italian) must work with NO add-on installed — an add-on the customer has to
# find and install is not "in the package". So the bundle is now en-US plus those six; the other
# 30 still ride in the Language Packs add-on. Cost is ~700 KB, which is what shipping the
# requested languages actually weighs.
$I18N_KEEP = @('en-US.json', 'en-GB.json', 'es-ES.json', 'fr-FR.json', 'it-IT.json', 'nl-NL.json', 'ur-PK.json', 'index.json')
$script:I18nAddOnFiles = @()
foreach ($i18nSub in @('builder\i18n')) {
    $i18nSrc = Join-Path "$assetsDir\js" $i18nSub
    if (Test-Path $i18nSrc) {
        $i18nDst = Join-Path "$RESOURCES\Assets\js" $i18nSub
        New-Item -ItemType Directory -Path $i18nDst -Force | Out-Null
        $n = 0
        Get-ChildItem "$i18nSrc\*.json" -File -ErrorAction SilentlyContinue | ForEach-Object {
            if ($I18N_KEEP -contains $_.Name) {
                Copy-Item $_.FullName $i18nDst -Force; $n++
            } else {
                $script:I18nAddOnFiles += $_
            }
        }
        Write-Host "  + Assets\js\$i18nSub\*.json  ($n bundled language file(s))" -ForegroundColor Green
        if ($script:I18nAddOnFiles.Count -gt 0) {
            Write-Host ("  - Assets\js\$i18nSub : {0} locale(s) moved to the Language Packs add-on ({1:N0} KB)" -f $script:I18nAddOnFiles.Count, (($script:I18nAddOnFiles | Measure-Object Length -Sum).Sum / 1KB)) -ForegroundColor Yellow
        }
    }
}

Get-ChildItem "$assetsDir\embed*.html" -ErrorAction SilentlyContinue | ForEach-Object {
    Copy-Item $_.FullName "$RESOURCES\Assets\" -Force
    Write-Host "  + Assets\$($_.Name)"
}

if (Test-Path "$assetsDir\themes") {
    New-Item -ItemType Directory -Path "$RESOURCES\Assets\themes" -Force | Out-Null
    Get-ChildItem "$assetsDir\themes\*" -File -ErrorAction SilentlyContinue | ForEach-Object {
        Copy-Item $_.FullName "$RESOURCES\Assets\themes\" -Force
    }
    Write-Host '  + Assets\themes\*'
}

# [DNN pack 2026-07-08] Runtime dirs the code reads but the script never shipped:
#  - Assets\img (megaform-ai-bear.png + flags/ for phone country picker)
#  - Resources\PromptRecipes + Resources\TemplateGuides (AiToolsController reads
#    ~/DesktopModules/MegaForm/Resources/...)
#  - Templates (BuilderTemplateCatalogService data root — seed the builder gallery)
# [FlagAllowList 2026-07-29] Assets\img\flags\4x3 carries 271 SVG; the country picker only ever
# asks for the 182 ISO2 codes in its own COUNTRIES table (country-picker.ts builds the URL as
# base + iso + '.svg', one request per rendered country — nothing enumerates the folder). The other
# 89 files are territories the picker cannot offer: 229 KB shipped to every customer for nothing.
# Derive the allow-list FROM THE CODE so the package can never drift from the picker.
$flagAllowList = @()
$countryPickerTs = Join-Path $SOLUTION_DIR 'MegaForm.UI\src\renderer\country-picker.ts'
if (Test-Path $countryPickerTs) {
    $flagAllowList = ([regex]::Matches((Get-Content $countryPickerTs -Raw), "iso2:\s*'([A-Za-z-]{2,6})'") |
        ForEach-Object { $_.Groups[1].Value.ToLowerInvariant() }) | Sort-Object -Unique
}
if ($flagAllowList.Count -lt 180) {
    throw ("Flag allow-list came back with only {0} entries - the COUNTRIES regex in BuildPackage-DNN.ps1 no longer matches country-picker.ts. Fix it before packaging, or every phone field ships without flags." -f $flagAllowList.Count)
}

if (Test-Path "$assetsDir\img") {
    New-Item -ItemType Directory -Path "$RESOURCES\Assets\img" -Force | Out-Null
    $imgSkipped = 0; $imgSkippedBytes = 0
    $flagSkipped = 0; $flagSkippedBytes = 0
    Get-ChildItem "$assetsDir\img\*" -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
        $rel = $_.FullName.Replace("$assetsDir\img\", '')
        if ($rel -match '^flags\\' -and $flagAllowList -notcontains $_.BaseName.ToLowerInvariant()) {
            $flagSkipped++; $flagSkippedBytes += $_.Length; return
        }
        # Template artwork now ships in the gallery's per-template assets zip and is
        # extracted on install, so keep it OUT of the package.
        if ($SLIM_GALLERY -and ($GALLERY_IMG -contains ($rel -replace '\\', '/'))) {
            $imgSkipped++; $imgSkippedBytes += $_.Length; return
        }
        if ($ORPHAN_IMG -contains ($rel -replace '\\', '/')) {
            $imgSkipped++; $imgSkippedBytes += $_.Length; return
        }
        $destDir = Join-Path "$RESOURCES\Assets\img" (Split-Path $rel)
        if ($destDir -and -not (Test-Path $destDir)) { New-Item -ItemType Directory -Path $destDir -Force | Out-Null }
        Copy-Item $_.FullName (Join-Path "$RESOURCES\Assets\img" $rel) -Force
    }
    if ($imgSkipped -gt 0) {
        Write-Host ("  - Assets\img: {0} gallery-hosted image(s) EXCLUDED ({1:N1} MB)" -f $imgSkipped, ($imgSkippedBytes/1MB)) -ForegroundColor Yellow
    }
    if ($flagSkipped -gt 0) {
        Write-Host ("  - Assets\img\flags: {0} flag(s) the picker never asks for EXCLUDED ({1:N0} KB)" -f $flagSkipped, ($flagSkippedBytes/1KB)) -ForegroundColor Yellow
    }
    $flagsShipped = @(Get-ChildItem "$RESOURCES\Assets\img\flags" -Recurse -File -ErrorAction SilentlyContinue).Count
    if ($flagsShipped -lt 180) {
        throw ("Only $flagsShipped flag(s) made it into the package - the phone country picker needs one per offered country. Check the allow-list.")
    }
    Write-Host ("  + Assets\img\* (bear + {0} flags)" -f $flagsShipped)
}
if (Test-Path "$assetsDir\fonts") {
    New-Item -ItemType Directory -Path "$RESOURCES\Assets\fonts" -Force | Out-Null
    # [FontSlim 2026-07-25] SKIP Assets\fonts\gf — a 12.9 MB self-hosted Google-Fonts download
    # (Inter/…) that NOTHING references: the shipped CSS pulls Inter/Geist from the Google Fonts
    # CDN (@import googleapis) and falls back to system fonts, so gf was pure dead weight that
    # doubled the package (13 → 25.6 MB). Copy every other font folder (euro-scroll, flags…).
    Get-ChildItem "$assetsDir\fonts\*" -ErrorAction SilentlyContinue | Where-Object { $_.Name -ne 'gf' } | ForEach-Object {
        Copy-Item $_.FullName "$RESOURCES\Assets\fonts\" -Recurse -Force
    }
    Write-Host '  + Assets\fonts\* (excluding gf: unreferenced self-hosted Google Fonts, ~12.9 MB)'
}
foreach ($resSub in @('PromptRecipes', 'TemplateGuides')) {
    $src = Join-Path $PROJECT_DIR "Resources\$resSub"
    if (Test-Path $src) {
        $dst = Join-Path $RESOURCES "Resources\$resSub"
        New-Item -ItemType Directory -Path $dst -Force | Out-Null
        Copy-Item "$src\*" $dst -Recurse -Force
        Write-Host "  + Resources\$resSub\*"
    }
}
# [KbSeedParity 2026-07-29] Ship the canonical AI-knowledge seed so DNN reaches the same KB
# as Oqtane/Web/Umbraco. Until now DNN only had the frozen SqlDataProvider inserts (64 entries
# against the seed's 329) and nothing topped it up at runtime; DnnKbSeeder merges this file on
# the first KB read. ~1.4 MB raw / ~0.17 MB in the zip.
$kbSeedSrc = Join-Path $SOLUTION_DIR 'MegaForm.Core\Seed\ai-knowledge-seed.json'
if (Test-Path $kbSeedSrc) {
    New-Item -ItemType Directory -Path "$RESOURCES\Seed" -Force | Out-Null
    Copy-Item $kbSeedSrc "$RESOURCES\Seed\" -Force
    Write-Host ("  + Seed\ai-knowledge-seed.json ({0:N2} MB raw - AI knowledge base)" -f ((Get-Item $kbSeedSrc).Length / 1MB)) -ForegroundColor Green
} else {
    throw "MegaForm.Core\Seed\ai-knowledge-seed.json is missing - the DNN KB would install at the SqlScripts subset only."
}

# [QuickStart 2026-07-24] The bundled shelf a fresh install opens with, in two parts:
#   1. Samples\FormTemplates\QuickStart  — 31 FREE starters (premium:false). These are what
#      makes a trial install usable: none of them is locked.
#   2. the BUNDLED premium starters from the gallery source — the paid designs on display.
#      Everything else in that folder is served from the gallery repo instead (SLIM).
# Keep this in step with tools\gallery\sync-bundled-templates.mjs, which composes the SAME
# two parts into the Oqtane payload.
New-Item -ItemType Directory -Path "$RESOURCES\Templates" -Force | Out-Null

$quickSrc = Join-Path $SOLUTION_DIR 'Samples\FormTemplates\QuickStart'
if (Test-Path $quickSrc) {
    $quickCount = 0
    Get-ChildItem "$quickSrc\*.json" -File -ErrorAction SilentlyContinue | ForEach-Object {
        Copy-Item $_.FullName "$RESOURCES\Templates\" -Force; $quickCount++
    }
    Write-Host ("  + Templates: {0} quick-start starter(s) (free, never locked on trial)" -f $quickCount) -ForegroundColor Green
} else {
    # Fail loudly: silently shipping only the premium starters is the "fresh install shows
    # nothing but locked cards" regression this folder exists to prevent.
    throw "Samples\FormTemplates\QuickStart is missing. Run: node tools/gallery/build-quickstart.mjs"
}

# [PremiumTemplatePath 2026-08-20] Thu muc premium ten la GALLERY-PUBLISHED, khong phai DONEE.
# DONEE la ten cu, da doi tu lau. Vi ca khoi nam trong `if (Test-Path $tplSrc)`, duong dan sai chi
# lam khoi bi bo qua IM LANG: goi build xong, khong mot canh bao nao, va thieu 4 template premium.
# Guard duoi day bien no thanh loi that thay vi im lang.
$tplSrc = Join-Path $SOLUTION_DIR 'Samples\FormTemplates\Premium\GALLERY-PUBLISHED'
if (-not (Test-Path $tplSrc)) {
    throw "Khong tim thay thu muc template premium: $tplSrc"
}
if (Test-Path $tplSrc) {
    if ($SLIM_GALLERY) {
        # Gallery-hosted templates are downloaded on demand (Template Gallery -> Browse
        # online) on licensed installs, so they no longer ship in the package.
        if (-not $GALLERY_KEEP -or $GALLERY_KEEP.Count -eq 0) {
            throw "gallery-exclude.json has no bundledFiles. Re-run: node tools/gallery/build-gallery.mjs --out <gallery-repo>"
        }
        $tplKept = 0; $tplSkipped = 0; $tplSkippedBytes = 0
        Get-ChildItem "$tplSrc\*" -File -ErrorAction SilentlyContinue | ForEach-Object {
            if ($GALLERY_KEEP -notcontains $_.Name) { $tplSkipped++; $tplSkippedBytes += $_.Length; return }
            Copy-Item $_.FullName "$RESOURCES\Templates\" -Force; $tplKept++
        }
        if ($tplKept -ne $GALLERY_KEEP.Count) {
            throw "Expected $($GALLERY_KEEP.Count) bundled premium starter(s) but copied $tplKept. Source folder and gallery-exclude.json disagree."
        }
        Write-Host ("  - Templates: {0} non-bundled template(s) EXCLUDED ({1:N2} MB), {2} premium starter(s) kept" -f $tplSkipped, ($tplSkippedBytes/1MB), $tplKept) -ForegroundColor Yellow
    } else {
        Copy-Item "$tplSrc\*" "$RESOURCES\Templates\" -Recurse -Force
        Write-Host '  + Templates\* (full premium set — KeepGalleryContent)'
    }
}

$samplesDir = "$SOLUTION_DIR\Samples"
if (-not (Test-Path $samplesDir)) { $samplesDir = "$PROJECT_DIR\Samples" }
if (Test-Path $samplesDir) {
    # [AzureResidue 2026-08-11] Top-level FILES only, deliberately. Do NOT add -Recurse here.
    #
    # Samples\AspNetCoreHost\bin\{Debug,Release}\net9.0 contains Azure.Core.dll, Azure.Identity.dll
    # and System.ClientModel.dll (they arrive legitimately, via Microsoft.Data.SqlClient ->
    # Azure.Identity). A recursive copy would sweep them into Resources.zip and put the exact
    # assembly that kills DNN's startup attribute scan onto every customer's disk, one manual copy
    # away from bin. See the [AzureResidue 2026-08-11] block in MegaForm.dnn for what that costs.
    #
    # The old form, Copy-Item "$samplesDir\*", also CREATED the sample subdirectories empty, which
    # looked like a packaging bug and invited exactly the -Recurse "fix" this comment is warning
    # against. Enumerating files removes the bait: no empty folders ship, and the package contents
    # are unchanged otherwise. The staging guard further down is the backstop if this ever slips.
    $sampleFiles = @(Get-ChildItem $samplesDir -File -ErrorAction SilentlyContinue)
    foreach ($sample in $sampleFiles) { Copy-Item $sample.FullName "$RESOURCES\Samples\" -Force }
    Write-Host ("  + Samples\* ({0} file(s), khong de quy)" -f $sampleFiles.Count)
}

if ($Trial) {
    Write-Host '  - license.lic OMITTED (TRIAL edition: install runs unlicensed)' -ForegroundColor Yellow
}
elseif (Test-Path "$PROJECT_DIR\license.lic") {
    Copy-Item "$PROJECT_DIR\license.lic" "$RESOURCES\license.lic" -Force
    Write-Host '  + license.lic (PRODUCTION edition)'
}

Write-Host ''
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\bundles\megaform-builder.js') -Label 'Packaged builder bundle'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\megaform-builder-loader.js') -Label 'Packaged builder loader'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\plugins\megaform-widget-qrcode.js') -Label 'Packaged QRCode plugin'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\plugins\megaform-widget-rich-text.js') -Label 'Packaged RichText widget'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\plugins\vendor\quill\quill.min.js') -Label 'Packaged self-hosted Quill runtime'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\css\plugins\vendor\quill\quill.snow.css') -Label 'Packaged self-hosted Quill theme'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\megaform-dashboard.js') -Label 'Packaged dashboard bundle'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\megaform-workflow-reactflow.js') -Label 'Packaged workflow canvas bundle'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\react.production.min.js') -Label 'Packaged React runtime'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\react-dom.production.min.js') -Label 'Packaged ReactDOM runtime'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\reactflow.min.js') -Label 'Packaged ReactFlow runtime'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\reactflow.min.css') -Label 'Packaged ReactFlow CSS'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\i18n\index.json') -Label 'Packaged i18n locale index'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\i18n\en-US.json') -Label 'Packaged English locale'
# [LocaleSwap 2026-08-13] Guard every language the owner requires in the package, not just one.
# This assert is what caught the swap: it still demanded vi-VN.json and failed the pack.
foreach ($reqLoc in @('en-GB', 'es-ES', 'fr-FR', 'it-IT', 'nl-NL', 'ur-PK')) {
    Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES "Assets\js\builder\i18n\$reqLoc.json") -Label "Packaged $reqLoc locale"
}
# [PkgSlim 2026-07-28] The locale files ship ONCE, in Assets\js\builder\i18n — the folder the
# browser fetches on DNN and the one ResolveI18nFolders()/ResolveWritableI18nFolder() land on.
# The guard moved with them; it still fails the build if a fresh install would ship no languages.
# [LanguagePacksAddOn 2026-07-29] The module now ships the DEFAULT pair plus the manifest; the
# other 36 locales live in the add-on. index.json is what the Languages panel lists from, so it
# must never leave the module.
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\i18n\index.json') -Label 'Packaged locale manifest'
$__i18nCount = (Get-ChildItem (Join-Path $RESOURCES 'Assets\js\builder\i18n\*.json') -File -ErrorAction SilentlyContinue | Measure-Object).Count
if ($__i18nCount -lt $I18N_KEEP.Count) { throw "Thieu language packs: chi co $__i18nCount/$($I18N_KEEP.Count) file trong Assets\js\builder\i18n" }
$__i18nSourceCount = (Get-ChildItem (Join-Path "$assetsDir\js" 'builder\i18n\*.json') -File -ErrorAction SilentlyContinue | Measure-Object).Count
if (($__i18nCount + $script:I18nAddOnFiles.Count) -ne $__i18nSourceCount) {
    throw "Language packs lost in packaging: $__i18nCount bundled + $($script:I18nAddOnFiles.Count) add-on != $__i18nSourceCount on disk"
}
# Nothing may ship a second copy: that duplication was 3.11 MB of the package.
foreach ($__dupI18n in @('Assets\js\i18n', 'Assets\js\bundles\i18n', 'Assets\js\plugins\i18n')) {
    if (Test-Path (Join-Path $RESOURCES $__dupI18n)) { throw "Duplicate locale folder crept back into the package: $__dupI18n" }
}
Write-Host "  [OK] Language packs: $__i18nCount files in Assets\js\builder\i18n (single copy)" -ForegroundColor Green
Write-Host ''

# ============================================================
#  4. Kiem tra Resources
# ============================================================
Write-Host '[4/7] Kiem tra Resources...' -ForegroundColor Yellow
$allRes = Get-ChildItem $RESOURCES -Recurse -File
Write-Host "  Tong files: $($allRes.Count)" -ForegroundColor Green
Write-Host ''

# ============================================================
#  5. Tao Resources.zip + Install ZIP
# ============================================================
Write-Host '[5/7] Tao Resources.zip...' -ForegroundColor Yellow

Add-Type -AssemblyName System.IO.Compression.FileSystem

$resourcesZip = Join-Path $STAGING 'Resources.zip'
if (Test-Path $resourcesZip) { Remove-Item $resourcesZip -Force }
[System.IO.Compression.ZipFile]::CreateFromDirectory($RESOURCES, $resourcesZip, [System.IO.Compression.CompressionLevel]::Optimal, $false)
Write-Host '  + Resources.zip [OK]' -ForegroundColor Green

# [PersonaBarMerge 2026-08-01] The panel's SPA. The root of this zip IS the Persona Bar's
# Modules folder, so entries must start at MegaForm/... — the loader resolves
# Modules/<folderName>/<path>.{html,js,css} straight from the menu row in the manifest.
$pbSrc = Join-Path $SOLUTION_DIR 'MegaForm.PersonaBar\Modules'
if (Test-Path (Join-Path $pbSrc 'MegaForm\MegaForm.html')) {
    $personaZip = Join-Path $STAGING 'PersonaBar.zip'
    if (Test-Path $personaZip) { Remove-Item $personaZip -Force }
    [System.IO.Compression.ZipFile]::CreateFromDirectory($pbSrc, $personaZip, [System.IO.Compression.CompressionLevel]::Optimal, $false)
    Write-Host '  + PersonaBar.zip [OK]' -ForegroundColor Green
} else {
    Write-Warning "Khong thay $pbSrc\MegaForm\MegaForm.html - panel se trong ruong."
}
Write-Host ''

Write-Host '[6/7] Tao Install Package...' -ForegroundColor Yellow

# [LockedOutput 2026-07-28] A browser that still has the previous zip open (uploading it to the
# store, say) keeps an exclusive handle on Windows and the whole build died on Remove-Item after
# doing all the work. Fall back to <name>.new.zip and say so, instead of throwing away the build.
if (Test-Path $OUTPUT_ZIP) {
    try {
        Remove-Item $OUTPUT_ZIP -Force -ErrorAction Stop
    } catch {
        $OUTPUT_ZIP = [System.IO.Path]::ChangeExtension($OUTPUT_ZIP, $null).TrimEnd('.') + '.new.zip'
        Write-Warning "File cu dang bi khoa boi tien trinh khac -> ghi ra: $(Split-Path $OUTPUT_ZIP -Leaf)"
        if (Test-Path $OUTPUT_ZIP) { Remove-Item $OUTPUT_ZIP -Force }
    }
}

# ============================================================
# [AzureResidue 2026-08-11] Last line of defence before anything is zipped.
#
# Shipping Azure.Core.dll once already cost a fleet of customer sites their Control Bar: DNN
# attribute-scans EVERY assembly in bin at startup, Azure.Core 1.55 carries an assembly-level
# attribute whose type lives in System.ClientModel, and with that assembly absent the scan throws
# and ExtensionPointManager stays faulted for the life of the app domain. The install reports
# success; the site just quietly loses Edit mode. Measured recovery: deleting the three files took
# ToggleUserMode from 500 back to 405.
#
# Every known route is closed by construction - the PackageReference is gone, $cloudDllNames is an
# allow-list, and the Samples copy is not recursive. This guard exists because those are three
# separate places, each one edit away from reopening the hole, and because the failure is invisible
# at build time and expensive at the customer's. Fail the build instead.
#
# Scoped to the crash set only. AWSSDK.* is the supported S3 add-on and must pass. On .NET 8/9/10
# hosts Azure.Core arrives legitimately through Microsoft.Data.SqlClient -> Azure.Identity, but no
# such payload belongs in a net472 DNN package, so an unqualified block is right HERE and would be
# wrong in the Oqtane/Umbraco scripts.
$forbiddenInPackage = @('Azure.Core.dll', 'Azure.Storage.Blobs.dll', 'Azure.Storage.Common.dll',
                        'Azure.Identity.dll', 'System.ClientModel.dll')
$staged = @(Get-ChildItem $STAGING -Recurse -File -ErrorAction SilentlyContinue |
            Where-Object { $forbiddenInPackage -contains $_.Name })
if ($staged.Count -gt 0) {
    $where = ($staged | ForEach-Object { $_.FullName.Substring($STAGING.Length).TrimStart('\') }) -join ', '
    throw ("Package staging chua {0} assembly Azure/ClientModel: {1}. Chung phai KHONG BAO GIO co " -f $staged.Count, $where) +
          "trong goi DNN: mot ban cai mang Azure.Core ma thieu System.ClientModel se lam chet " +
          "Control Bar cua site (500) suot doi app domain. Xem khoi [AzureResidue 2026-08-11] " +
          "trong MegaForm.dnn."
}
Write-Host ("  [OK] khong co assembly Azure/ClientModel nao trong staging ({0} ten bi cam)" -f $forbiddenInPackage.Count) -ForegroundColor Green

$zip = [System.IO.Compression.ZipFile]::Open($OUTPUT_ZIP, 'Create')

@('MegaForm.dnn', 'License.txt', 'ReleaseNotes.txt', 'icon.gif', 'Resources.zip', 'PersonaBar.zip') +
    @($cleanupNames | Where-Object { $_ }) | ForEach-Object {
    $fp = Join-Path $STAGING $_
    if (Test-Path $fp) {
        [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $fp, $_) | Out-Null
    }
}

Get-ChildItem "$STAGING\bin" -File | ForEach-Object {
    [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $_.FullName, "bin/$($_.Name)") | Out-Null
}

Get-ChildItem "$STAGING\SqlScripts" -File | ForEach-Object {
    [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $_.FullName, "SqlScripts/$($_.Name)") | Out-Null
}

$zip.Dispose()

# [ManifestZipParity 2026-08-14] Every <file>/<assembly> the manifest declares must actually BE in
# the zip. Both staging copies above are best-effort — a missing icon.gif is skipped without a
# word, and a missing MegaForm.PersonaBar.dll only prints a Write-Warning that scrolls past in a
# long build. 02.00.019 shipped that way (4.2 MB instead of 7.5 MB) and DNN refused it at install:
#   Failure File specified in the dnn could not be found in the zip file: ...\icon.gif
#   Failure File specified in the dnn could not be found in the zip file: ...\bin\MegaForm.PersonaBar.dll
# The install log is the WRONG place to learn this. Check it here, where the build can still fail.
$manifestXml = [xml](Get-Content $MANIFEST -Raw)
$declaredEntries = @()
foreach ($node in $manifestXml.SelectNodes('//component[@type="File"]/files/file')) {
    $base = ''
    if ($node.ParentNode.basePath) { $base = ($node.ParentNode.basePath -replace '\\', '/').Trim('/') + '/' }
    $declaredEntries += ($base + $node.name)
}
foreach ($node in $manifestXml.SelectNodes('//component[@type="Assembly"]/assemblies/assembly')) {
    $base = ''
    if ($node.path) { $base = ($node.path -replace '\\', '/').Trim('/') + '/' }
    $declaredEntries += ($base + $node.name)
}
$declaredEntries = @($declaredEntries | Where-Object { $_ } | Sort-Object -Unique)

$verifyZip = [System.IO.Compression.ZipFile]::OpenRead($OUTPUT_ZIP)
try {
    $zipEntryNames = @($verifyZip.Entries | ForEach-Object { $_.FullName })
} finally {
    $verifyZip.Dispose()
}
$missingEntries = @($declaredEntries | Where-Object { $zipEntryNames -notcontains $_ })
if ($missingEntries.Count -gt 0) {
    Remove-Item $OUTPUT_ZIP -Force -ErrorAction SilentlyContinue
    throw ("MegaForm.dnn khai {0} file KHONG co trong zip: {1}. DNN se tu choi cai goi nay. " -f $missingEntries.Count, ($missingEntries -join ', ')) +
          "MegaForm.PersonaBar.dll thieu => build no truoc: dotnet build MegaForm.PersonaBar\MegaForm.PersonaBar.csproj -c Release. " +
          "Goi hong da bi xoa de khong ai cai nham."
}
Write-Host ("  [OK] {0} file manifest khai deu co trong zip" -f $declaredEntries.Count) -ForegroundColor Green

# ------------------------------------------------------------
# [S3AddOn 2026-07-28] Optional add-on: Amazon S3 storage provider.
# A DNN "Library" package carrying only MegaForm.Integrations.CloudStorage.dll + the AWS SDK
# (~0.73 MB). Kept out of the module package because only S3-mirroring installs run that code
# and the module has to fit the store's upload limit. Install order does not matter — the
# module resolves the provider by reflection on every app start.
# ------------------------------------------------------------
$addonDir = Join-Path $OUTPUT_DIR '_s3addon'
if (Test-Path $addonDir) { Remove-Item $addonDir -Recurse -Force }
New-Item -ItemType Directory -Path "$addonDir\bin" -Force | Out-Null
$addonCopied = 0
foreach ($name in $cloudDllNames) {
    $src = Join-Path (Split-Path $dnnDll) $name
    if (Test-Path $src) { Copy-Item $src "$addonDir\bin\" -Force; $addonCopied++ }
    else { Write-Warning "S3 add-on DLL khong tim thay (bo qua): $name" }
}
if ($addonCopied -gt 0) {
    $addonAssemblies = ($cloudDllNames | ForEach-Object {
        "            <assembly>`r`n              <name>$_</name>`r`n              <path>bin</path>`r`n            </assembly>"
    }) -join "`r`n"
    $addonManifest = @"
<dotnetnuke type="Package" version="5.0">
  <packages>
    <package name="MegaForm.CloudStorageS3" type="Library" version="$VERSION">
      <friendlyName>MegaForm Cloud Storage - Amazon S3</friendlyName>
      <description>Optional add-on for MegaForm: mirrors submission file uploads to an Amazon S3 bucket. Install it only if you configure an S3 connection; MegaForm works without it (Google Drive stays built in).</description>
      <iconFile></iconFile>
      <owner>
        <name>CISS Solution</name>
        <organization>CISS Solution</organization>
        <url></url>
        <email></email>
      </owner>
      <license></license>
      <releaseNotes>Ships MegaForm.Integrations.CloudStorage.dll + AWSSDK.Core + AWSSDK.S3, which used to ride inside the MegaForm module package.</releaseNotes>
      <azureCompatible>true</azureCompatible>
      <dependencies />
      <components>
        <component type="Assembly">
          <assemblies>
$addonAssemblies
          </assemblies>
        </component>
      </components>
    </package>
  </packages>
</dotnetnuke>
"@
    Set-Content -Path "$addonDir\MegaForm.CloudStorageS3.dnn" -Value $addonManifest -Encoding UTF8
    $addonZip = Join-Path $OUTPUT_DIR "MegaForm.CloudStorageS3_${VERSION}_Install.zip"
    if (Test-Path $addonZip) { Remove-Item $addonZip -Force }
    $az = [System.IO.Compression.ZipFile]::Open($addonZip, 'Create')
    [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($az, "$addonDir\MegaForm.CloudStorageS3.dnn", 'MegaForm.CloudStorageS3.dnn') | Out-Null
    Get-ChildItem "$addonDir\bin" -File | ForEach-Object {
        [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($az, $_.FullName, "bin/$($_.Name)") | Out-Null
    }
    $az.Dispose()
    Write-Host ("  + S3 add-on: {0} ({1:N1} KB)" -f (Split-Path $addonZip -Leaf), ((Get-Item $addonZip).Length / 1KB)) -ForegroundColor Cyan
}
Remove-Item $addonDir -Recurse -Force

# ------------------------------------------------------------
# [CodeEditorAddOn 2026-07-28] Optional add-on: the Monaco code editor bundle.
# A ResourceFile package that drops megaform-unified-monaco.js back into
# DesktopModules/MegaForm/Assets/js — the exact path the builder's script tag asks for, so
# nothing else changes once it is installed. Without it the Source/Razor tab degrades to a
# <textarea>, which is what an air-gapped install already gets.
# ------------------------------------------------------------
$editorSrc = Join-Path "$assetsDir\js" $CODE_EDITOR_JS
if (Test-Path $editorSrc) {
    $edDir = Join-Path $OUTPUT_DIR '_editoraddon'
    if (Test-Path $edDir) { Remove-Item $edDir -Recurse -Force }
    New-Item -ItemType Directory -Path "$edDir\payload\Assets\js" -Force | Out-Null
    Copy-Item $editorSrc "$edDir\payload\Assets\js\" -Force
    $edResources = Join-Path $edDir 'Resources.zip'
    [System.IO.Compression.ZipFile]::CreateFromDirectory("$edDir\payload", $edResources, [System.IO.Compression.CompressionLevel]::Optimal, $false)
    $edManifest = @"
<dotnetnuke type="Package" version="5.0">
  <packages>
    <package name="MegaForm.CodeEditor" type="Library" version="$VERSION">
      <friendlyName>MegaForm Code Editor (Monaco)</friendlyName>
      <description>Optional add-on for MegaForm: the Monaco editor used by the Source / Razor / Custom HTML tabs. Without it those tabs fall back to a plain textarea; everything else works the same.</description>
      <iconFile></iconFile>
      <owner>
        <name>CISS Solution</name>
        <organization>CISS Solution</organization>
        <url></url>
        <email></email>
      </owner>
      <license></license>
      <releaseNotes>Ships Assets/js/megaform-unified-monaco.js, which used to ride inside the MegaForm module package (1.02 MB).</releaseNotes>
      <azureCompatible>true</azureCompatible>
      <dependencies />
      <components>
        <component type="ResourceFile">
          <resourceFiles>
            <basePath>DesktopModules/MegaForm</basePath>
            <resourceFile>
              <name>Resources.zip</name>
            </resourceFile>
          </resourceFiles>
        </component>
      </components>
    </package>
  </packages>
</dotnetnuke>
"@
    Set-Content -Path "$edDir\MegaForm.CodeEditor.dnn" -Value $edManifest -Encoding UTF8
    $edZip = Join-Path $OUTPUT_DIR "MegaForm.CodeEditor_${VERSION}_Install.zip"
    if (Test-Path $edZip) { Remove-Item $edZip -Force }
    $ez = [System.IO.Compression.ZipFile]::Open($edZip, 'Create')
    [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($ez, "$edDir\MegaForm.CodeEditor.dnn", 'MegaForm.CodeEditor.dnn') | Out-Null
    [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($ez, $edResources, 'Resources.zip') | Out-Null
    $ez.Dispose()
    Remove-Item $edDir -Recurse -Force
    Write-Host ("  + Code editor add-on: {0} ({1:N1} KB)" -f (Split-Path $edZip -Leaf), ((Get-Item $edZip).Length / 1KB)) -ForegroundColor Cyan
} else {
    Write-Warning "Khong tim thay $CODE_EDITOR_JS - bo qua goi code editor add-on."
}

# ------------------------------------------------------------
# [LanguagePacksAddOn 2026-07-29] Optional add-on: the 36 locales the module no longer bundles.
# Same ResourceFile shape as the code editor: DNN unzips them straight back into
# DesktopModules/MegaForm/Assets/js/builder/i18n - the exact folder the browser fetches and the
# Languages panel writes to - so no application code changes once it is installed. Without it a
# site runs the seven bundled locales (see $I18N_KEEP), and loadLocale() already falls back to
# en-US on a 404.
# ------------------------------------------------------------
if ($script:I18nAddOnFiles.Count -gt 0) {
    $lpDir = Join-Path $OUTPUT_DIR '_langpacks'
    if (Test-Path $lpDir) { Remove-Item $lpDir -Recurse -Force }
    New-Item -ItemType Directory -Path "$lpDir\payload\Assets\js\builder\i18n" -Force | Out-Null
    foreach ($lp in $script:I18nAddOnFiles) { Copy-Item $lp.FullName "$lpDir\payload\Assets\js\builder\i18n\" -Force }
    $lpResources = Join-Path $lpDir 'Resources.zip'
    [System.IO.Compression.ZipFile]::CreateFromDirectory("$lpDir\payload", $lpResources, [System.IO.Compression.CompressionLevel]::Optimal, $false)
    $lpNames = ($script:I18nAddOnFiles | ForEach-Object { $_.BaseName }) -join ', '
    $lpManifest = @"
<dotnetnuke type="Package" version="5.0">
  <packages>
    <package name="MegaForm.LanguagePacks" type="Library" version="$VERSION">
      <friendlyName>MegaForm Language Packs</friendlyName>
      <description>Optional add-on for MegaForm: $($script:I18nAddOnFiles.Count) extra admin-UI languages. The module itself ships English (US and UK), Spanish, French, Italian, Dutch and Urdu; install this to offer the rest. Nothing else changes - the files land in the folder MegaForm already reads.</description>
      <iconFile></iconFile>
      <owner>
        <name>CISS Solution</name>
        <organization>CISS Solution</organization>
        <url></url>
        <email></email>
      </owner>
      <license></license>
      <releaseNotes>Locales: $lpNames. These used to ride inside the MegaForm module package (1.06 MB compressed).</releaseNotes>
      <azureCompatible>true</azureCompatible>
      <dependencies />
      <components>
        <component type="ResourceFile">
          <resourceFiles>
            <basePath>DesktopModules/MegaForm</basePath>
            <resourceFile>
              <name>Resources.zip</name>
            </resourceFile>
          </resourceFiles>
        </component>
      </components>
    </package>
  </packages>
</dotnetnuke>
"@
    Set-Content -Path "$lpDir\MegaForm.LanguagePacks.dnn" -Value $lpManifest -Encoding UTF8
    $lpZip = Join-Path $OUTPUT_DIR "MegaForm.LanguagePacks_${VERSION}_Install.zip"
    if (Test-Path $lpZip) { Remove-Item $lpZip -Force }
    $lz = [System.IO.Compression.ZipFile]::Open($lpZip, 'Create')
    [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($lz, "$lpDir\MegaForm.LanguagePacks.dnn", 'MegaForm.LanguagePacks.dnn') | Out-Null
    [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($lz, $lpResources, 'Resources.zip') | Out-Null
    $lz.Dispose()
    Remove-Item $lpDir -Recurse -Force
    Write-Host ("  + Language packs add-on: {0} ({1} locales, {2:N1} KB)" -f (Split-Path $lpZip -Leaf), $script:I18nAddOnFiles.Count, ((Get-Item $lpZip).Length / 1KB)) -ForegroundColor Cyan
}

# ============================================================
#  7. Don dep + Ket qua
# ============================================================
Write-Host '[7/7] Don dep...' -ForegroundColor Yellow
Remove-Item $STAGING -Recurse -Force

$zipSize = [math]::Round((Get-Item $OUTPUT_ZIP).Length / 1KB, 1)
Write-Host ''
Write-Host '============================================================' -ForegroundColor Green
Write-Host '  HOAN THANH!' -ForegroundColor Green
Write-Host '============================================================' -ForegroundColor Green
Write-Host ''
Write-Host "  Edition: $EDITION $(if ($Trial) { '(no license.lic -> trial caps apply)' } else { '(license.lic=production -> unlimited)' })" -ForegroundColor $(if ($Trial) { 'Yellow' } else { 'Green' })
Write-Host "  Gallery: $(if ($SLIM_GALLERY) { "SLIM - $($GALLERY_TPL.Count) templates + $($GALLERY_IMG.Count) images served from the gallery repo" } else { 'FULL - templates + artwork bundled in the package' })" -ForegroundColor $(if ($SLIM_GALLERY) { 'Cyan' } else { 'Gray' })
Write-Host "  File: $OUTPUT_ZIP" -ForegroundColor White
Write-Host "  Size: ${zipSize} KB" -ForegroundColor White
Write-Host ''
Write-Host '  Package chua:' -ForegroundColor Gray
Write-Host "    MegaForm.dnn               (manifest v$VERSION)" -ForegroundColor Gray
Write-Host '    bin\MegaForm.DNN.dll       (DNN module)' -ForegroundColor Cyan
Write-Host '    bin\MegaForm.Core.dll      (Core shared library)' -ForegroundColor Cyan
Write-Host '    SqlScripts\*.SqlDataProvider' -ForegroundColor Gray
Write-Host '    Resources.zip              (Views + Assets)' -ForegroundColor Gray
Write-Host ''
Write-Host '  Cai dat: DNN -> Host -> Extensions -> Install Extension' -ForegroundColor Yellow
Write-Host ''
if (-not $NoPause) {
    Read-Host 'Nhan Enter de thoat'
}
