# ============================================================
#  MegaForm.DNN - DNN Install Package Creator
#
#  Tao file Install ZIP cai dat qua DNN Host > Extensions.
#  Chay: powershell -ExecutionPolicy Bypass -File BuildPackage-DNN.ps1
#
#  Mac dinh script nay co the tu build TypeScript + dotnet build
#  truoc khi package khi duoc goi tu BuildPackage-DNN.bat.
# ============================================================

[CmdletBinding()]
param(
    [switch]$BuildTS,
    [switch]$BuildDotNet,
    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Release',
    # [LicenseEdition 2026-07-24] -Trial builds the TRIAL edition: the license.lic marker is
    # OMITTED from the package, so a fresh install runs unlicensed (form/submission caps + AI
    # lock apply). Without -Trial the PRODUCTION edition ships license.lic="production" (unlimited).
    # The two editions are otherwise byte-identical. Zip name gets a _Trial suffix so the artifacts
    # never collide.
    [switch]$Trial,
    # [GalleryRepo 2026-07-24] Premium templates + their artwork are published to the
    # gallery repo and downloaded on demand, so NEITHER edition ships them. Trial has no
    # premium templates at all and cannot reach the gallery (402) — that is the product
    # model: the premium set is part of what a license buys.
    # Pass -KeepGalleryContent to build a self-contained package anyway.
    [switch]$KeepGalleryContent,
    [switch]$NoPause
)

$ErrorActionPreference = 'Stop'
$MODULE_NAME  = 'MegaForm'
$PROJECT_DIR  = Split-Path -Parent $MyInvocation.MyCommand.Path
$SOLUTION_DIR = Split-Path -Parent $PROJECT_DIR

# [DNN version single-source 2026-07-18] Derive the package version from the manifest so the
# build script and MegaForm.dnn can NEVER drift. They HAD drifted: this script hard-coded
# 01.07.106 while MegaForm.dnn declares 01.07.108, so the generated zip name lied about its
# version and shipped an install artifact built before 01.06.39.SqlDataProvider existed.
$MANIFEST     = Join-Path $PROJECT_DIR 'MegaForm.dnn'
$verMatch     = Select-String -Path $MANIFEST -Pattern '<package name="MegaForm"[^>]*version="([0-9.]+)"'
if (-not $verMatch) { throw "Khong doc duoc <package version> tu MegaForm.dnn" }
$VERSION      = $verMatch.Matches[0].Groups[1].Value
$STAGING      = Join-Path $PROJECT_DIR '_package'
$RESOURCES    = Join-Path $STAGING '_resources'
$OUTPUT_DIR   = Join-Path $PROJECT_DIR 'Install'
$EDITION      = if ($Trial) { 'Trial' } else { 'Production' }

# ── gallery-hosted content (generated by tools/gallery/build-gallery.mjs) ──
# Reading the generated list (never a hard-coded one) keeps the package exactly in
# sync with what the gallery actually serves: publish a new template and both update.
$SLIM_GALLERY = -not $KeepGalleryContent
$GALLERY_TPL  = @()
$GALLERY_IMG  = @()
$GALLERY_KEEP = @()
if ($SLIM_GALLERY) {
    $exclPath = Join-Path $SOLUTION_DIR 'tools\gallery\gallery-exclude.json'
    if (Test-Path $exclPath) {
        try {
            $excl = Get-Content $exclPath -Raw | ConvertFrom-Json
            $GALLERY_TPL = @($excl.templateFiles)
            $GALLERY_IMG = @($excl.images)
            # Allow-LIST, not deny-list: copy exactly the named bundled starters. A deny-list
            # ("anything not gallery-hosted") also ships whatever the publisher REFUSED —
            # which is how DNN ended up with 8 premium starters against Oqtane's 4.
            $GALLERY_KEEP = @($excl.bundledFiles)
        } catch {
            throw "gallery-exclude.json is unreadable: $($_.Exception.Message). Re-run tools/gallery/build-gallery.mjs."
        }
    } else {
        # Fail loudly: silently shipping the full package would hide the regression.
        throw "SLIM build requested but tools/gallery/gallery-exclude.json is missing. Run: node tools/gallery/build-gallery.mjs --out <gallery-repo>"
    }
}
$EDITION_TAG  = if ($Trial) { '_Trial' } else { '' }
$OUTPUT_ZIP   = Join-Path $OUTPUT_DIR "${MODULE_NAME}_${VERSION}${EDITION_TAG}_Install.zip"
$ROOT_BUILDTS_BAT = Join-Path $SOLUTION_DIR 'BuildTS.bat'
$DNN_CSPROJ       = Join-Path $PROJECT_DIR 'MegaForm.DNN.csproj'

function Assert-CommandAvailable {
    param(
        [Parameter(Mandatory = $true)][string]$CommandName,
        [Parameter(Mandatory = $true)][string]$FriendlyName
    )
    if (-not (Get-Command $CommandName -ErrorAction SilentlyContinue)) {
        throw "$FriendlyName khong tim thay trong PATH."
    }
}

function Assert-RequiredFile {
    param(
        [Parameter(Mandatory = $true)][string]$PathToCheck,
        [Parameter(Mandatory = $true)][string]$Label
    )
    if (-not (Test-Path $PathToCheck)) {
        throw "Thieu file bat buoc: $Label -> $PathToCheck"
    }
    Write-Host "  [OK] $Label" -ForegroundColor Green
}

function Invoke-Step {
    param(
        [Parameter(Mandatory = $true)][string]$Title,
        [Parameter(Mandatory = $true)][scriptblock]$Action
    )
    Write-Host $Title -ForegroundColor Yellow
    & $Action
    Write-Host ''
}

Write-Host ''
Write-Host '============================================================' -ForegroundColor Cyan
Write-Host "  $MODULE_NAME - DNN Install Package v$VERSION" -ForegroundColor Cyan
Write-Host '============================================================' -ForegroundColor Cyan
Write-Host ''

# ============================================================
#  0. Pre-build (optional but enabled by BuildPackage-DNN.bat)
# ============================================================
if ($BuildTS) {
    Invoke-Step '[0/7] Build TypeScript bundles...' {
        Assert-CommandAvailable -CommandName 'powershell' -FriendlyName 'PowerShell'
        if (-not (Test-Path $ROOT_BUILDTS_BAT)) {
            throw "Khong tim thay BuildTS.bat tai root solution: $ROOT_BUILDTS_BAT"
        }
        & $ROOT_BUILDTS_BAT
        if ($LASTEXITCODE -ne 0) {
            throw "BuildTS.bat that bai voi ma loi $LASTEXITCODE"
        }
    }
}

if ($BuildDotNet) {
    Invoke-Step "[0b/7] Build MegaForm.DNN ($Configuration)..." {
        Assert-CommandAvailable -CommandName 'dotnet' -FriendlyName '.NET SDK'
        if (-not (Test-Path $DNN_CSPROJ)) {
            throw "Khong tim thay csproj: $DNN_CSPROJ"
        }
        dotnet build $DNN_CSPROJ -c $Configuration
        if ($LASTEXITCODE -ne 0) {
            throw "dotnet build MegaForm.DNN that bai voi ma loi $LASTEXITCODE"
        }
    }
}

# ============================================================
#  1. Tim DLL
# ============================================================
Write-Host '[1/7] Tim DLLs...' -ForegroundColor Yellow

$dnnDllPaths = @(
    "$PROJECT_DIR\bin\$Configuration\net472\MegaForm.DNN.dll",
    "$PROJECT_DIR\bin\$Configuration\MegaForm.DNN.dll",
    "$PROJECT_DIR\bin\Release\net472\MegaForm.DNN.dll",
    "$PROJECT_DIR\bin\Debug\net472\MegaForm.DNN.dll",
    "$PROJECT_DIR\bin\Release\MegaForm.DNN.dll",
    "$PROJECT_DIR\bin\Debug\MegaForm.DNN.dll"
)
$dnnDll = $null
foreach ($p in $dnnDllPaths) {
    if (Test-Path $p) { $dnnDll = $p; break }
}
if (-not $dnnDll) {
    throw 'MegaForm.DNN.dll khong tim thay! Hay build truoc: dotnet build -c Release'
}
Write-Host "  MegaForm.DNN.dll: $dnnDll" -ForegroundColor Green

$coreDll = Join-Path (Split-Path $dnnDll) 'MegaForm.Core.dll'
if (-not (Test-Path $coreDll)) {
    $coreDll = @(
        "$SOLUTION_DIR\MegaForm.Core\bin\$Configuration\net472\MegaForm.Core.dll",
        "$SOLUTION_DIR\MegaForm.Core\bin\Release\net472\MegaForm.Core.dll",
        "$SOLUTION_DIR\MegaForm.Core\bin\Debug\net472\MegaForm.Core.dll"
    ) | Where-Object { Test-Path $_ } | Select-Object -First 1
}
if (-not $coreDll -or -not (Test-Path $coreDll)) {
    throw 'MegaForm.Core.dll khong tim thay! Build Core/DNN truoc khi package.'
}
Write-Host "  MegaForm.Core.dll: $coreDll" -ForegroundColor Green

# [2026-06-23] MegaForm.Sdk.dll — DnnServiceLocator..ctor() loads it; omitting it from
# the package broke FormsOverview / Reports / scheduler tasks at runtime. Bundle it.
$sdkDll = Join-Path (Split-Path $dnnDll) 'MegaForm.Sdk.dll'
if (-not (Test-Path $sdkDll)) {
    $sdkDll = @(
        "$SOLUTION_DIR\MegaForm.Sdk\bin\$Configuration\net472\MegaForm.Sdk.dll",
        "$SOLUTION_DIR\MegaForm.Sdk\bin\Release\net472\MegaForm.Sdk.dll",
        "$SOLUTION_DIR\MegaForm.Sdk\bin\Debug\net472\MegaForm.Sdk.dll"
    ) | Where-Object { Test-Path $_ } | Select-Object -First 1
}
if (-not $sdkDll -or -not (Test-Path $sdkDll)) {
    throw 'MegaForm.Sdk.dll khong tim thay! Build Sdk/Core/DNN truoc khi package.'
}
Write-Host "  MegaForm.Sdk.dll: $sdkDll" -ForegroundColor Green

$dapperDll = Join-Path (Split-Path $dnnDll) 'Dapper.dll'
Write-Host ''

# ============================================================
#  2. Don dep + tao thu muc
# ============================================================
Write-Host '[2/7] Chuan bi thu muc...' -ForegroundColor Yellow

if (Test-Path $STAGING) { Remove-Item $STAGING -Recurse -Force }

@(
    $STAGING, "$STAGING\bin", "$STAGING\SqlScripts",
    "$RESOURCES\Views",
    "$RESOURCES\Assets\css", "$RESOURCES\Assets\css\plugins",
    "$RESOURCES\Assets\js", "$RESOURCES\Assets\js\builder",
    "$RESOURCES\Assets\js\bundles",
    "$RESOURCES\Assets\js\plugins", "$RESOURCES\Assets\js\locales",
    "$RESOURCES\Assets\Images", "$RESOURCES\Samples",
    "$RESOURCES\Images",
    $OUTPUT_DIR
) | ForEach-Object {
    if (-not (Test-Path $_)) { New-Item -ItemType Directory -Path $_ -Force | Out-Null }
}

# ============================================================
#  2b. TypeScript bundles / workflow assets verification
# ============================================================
$bundlesDir = Join-Path $SOLUTION_DIR 'Assets\js\bundles'
$builderDir = Join-Path $SOLUTION_DIR 'Assets\js\builder'
if (-not (Test-Path $bundlesDir)) {
    throw "Assets\js\bundles\ khong tim thay - can chay BuildTS.bat truoc khi package."
}
$bundleCount = (Get-ChildItem "$bundlesDir\*.js" -ErrorAction SilentlyContinue).Count
Write-Host "[2b] Found $bundleCount TS bundles in Assets\js\bundles\" -ForegroundColor Green
Assert-RequiredFile -PathToCheck (Join-Path $bundlesDir 'megaform-builder.js') -Label 'Builder bundle'
Assert-RequiredFile -PathToCheck (Join-Path $SOLUTION_DIR 'Assets\js\megaform-builder-loader.js') -Label 'Builder loader'
Assert-RequiredFile -PathToCheck (Join-Path $SOLUTION_DIR 'Assets\js\plugins\megaform-widget-qrcode.js') -Label 'QRCode plugin'
Assert-RequiredFile -PathToCheck (Join-Path $SOLUTION_DIR 'Assets\js\megaform-dashboard.js') -Label 'Dashboard bundle'
Assert-RequiredFile -PathToCheck (Join-Path $builderDir 'megaform-workflow-reactflow.js') -Label 'Workflow canvas bundle'
Assert-RequiredFile -PathToCheck (Join-Path $builderDir 'react.production.min.js') -Label 'React runtime'
Assert-RequiredFile -PathToCheck (Join-Path $builderDir 'react-dom.production.min.js') -Label 'ReactDOM runtime'
Assert-RequiredFile -PathToCheck (Join-Path $builderDir 'reactflow.min.js') -Label 'ReactFlow runtime'
Assert-RequiredFile -PathToCheck (Join-Path $builderDir 'reactflow.min.css') -Label 'ReactFlow CSS'
Write-Host ''

# ============================================================
#  3. Copy files
# ============================================================
Write-Host '[3/7] Copy files...' -ForegroundColor Yellow

Copy-Item "$PROJECT_DIR\MegaForm.dnn" "$STAGING\" -Force
Write-Host '  + MegaForm.dnn'

# [DNN sync 2026-06-22] icon.gif is declared in the manifest's <component type="File"> at the
# package root but was never copied/zipped — add it so the install matches the manifest.
$iconSrc = @("$PROJECT_DIR\Images\icon.gif", "$PROJECT_DIR\Install\icon.gif", "$PROJECT_DIR\icon.gif") |
    Where-Object { Test-Path $_ } | Select-Object -First 1
if ($iconSrc) {
    Copy-Item $iconSrc "$STAGING\icon.gif" -Force
    Write-Host '  + icon.gif'
}

# [ModuleIcon v20260716-01] The manifest's <iconFile> points at
# ~/DesktopModules/MegaForm/Images/module-icon.png, and the DB Packages.IconFile row matches —
# but the Images folder was never shipped in Resources.zip, so installed sites 404 the icon and
# the Add-Module list shows MegaForm without one (owner report). Ship the module Images folder.
foreach ($img in @("$PROJECT_DIR\Images\module-icon.png", "$PROJECT_DIR\Images\icon.gif")) {
    if (Test-Path $img) {
        Copy-Item $img "$RESOURCES\Images\" -Force
        Write-Host ('  + Images\' + (Split-Path $img -Leaf))
    }
}

if (Test-Path "$PROJECT_DIR\License.txt") {
    Copy-Item "$PROJECT_DIR\License.txt" "$STAGING\" -Force
} else {
    "MegaForm Module for DNN`r`nCopyright (c) 2025. All rights reserved.`r`nMIT License" | Out-File "$STAGING\License.txt" -Encoding UTF8
}

if (Test-Path "$PROJECT_DIR\ReleaseNotes.txt") {
    Copy-Item "$PROJECT_DIR\ReleaseNotes.txt" "$STAGING\" -Force
} else {
    $releaseNotes = @'
<h3>MegaForm v1.5.0</h3>
<ul>
  <li>Architecture: Split into MegaForm.Core + MegaForm.DNN</li>
  <li>Row/Column layout support in builder and public view</li>
  <li>Workflows, Permissions, Views, Templates (Phase 2)</li>
  <li>Webhook with HMAC-SHA256 signatures</li>
  <li>Anti-spam: honeypot + rate limit + heuristic scoring</li>
  <li>Save and Continue with resume tokens</li>
  <li>18+ field types, drag-and-drop builder</li>
  <li>TypeScript UI bundles for cross-platform support</li>
</ul>
'@
    $releaseNotes | Out-File "$STAGING\ReleaseNotes.txt" -Encoding UTF8
}

Copy-Item $dnnDll "$STAGING\bin\" -Force
Write-Host '  + bin\MegaForm.DNN.dll'
Copy-Item $coreDll "$STAGING\bin\" -Force
Write-Host '  + bin\MegaForm.Core.dll'
Copy-Item $sdkDll "$STAGING\bin\" -Force
Write-Host '  + bin\MegaForm.Sdk.dll'
if ($dapperDll -and (Test-Path $dapperDll)) {
    Copy-Item $dapperDll "$STAGING\bin\" -Force
    Write-Host '  + bin\Dapper.dll'
}

# [CloudStorage v20260723-01] Cloud storage provider DLLs (Google Drive / S3 / Azure Blob mirror).
# Copied from the DNN build output (they flow there via the MegaForm.Integrations.CloudStorage
# project reference). Only direct feature deps — Microsoft.Extensions.*/System.* stay out on
# purpose (DNN 10 already ships them; overwriting risks assembly-version conflicts).
$cloudDllNames = @(
    'MegaForm.Integrations.CloudStorage.dll',
    'AWSSDK.Core.dll',
    'AWSSDK.S3.dll',
    'Azure.Core.dll',
    'Azure.Storage.Blobs.dll',
    'Azure.Storage.Common.dll'
)
foreach ($name in $cloudDllNames) {
    $src = Join-Path (Split-Path $dnnDll) $name
    if (Test-Path $src) {
        Copy-Item $src "$STAGING\bin\" -Force
        Write-Host "  + bin\$name"
    } else {
        Write-Warning "Cloud storage DLL khong tim thay (bo qua): $name"
    }
}

# [DNN sync 2026-06-22] DNN scripts are *.SqlDataProvider (not *.sql); the old `*.sql` glob copied
# ZERO scripts so installs/upgrades shipped no schema. Copy both extensions.
Get-ChildItem "$PROJECT_DIR\SqlScripts\*" -Include *.SqlDataProvider, *.sql -ErrorAction SilentlyContinue | ForEach-Object {
    Copy-Item $_.FullName "$STAGING\SqlScripts\" -Force
    Write-Host "  + SqlScripts\$($_.Name)"
}

Get-ChildItem "$PROJECT_DIR\Views\*.ascx" -ErrorAction SilentlyContinue | ForEach-Object {
    Copy-Item $_.FullName "$RESOURCES\Views\" -Force
    Write-Host "  + Views\$($_.Name)"
}

$assetsDir = "$SOLUTION_DIR\Assets"
if (-not (Test-Path $assetsDir)) {
    $assetsDir = "$PROJECT_DIR\Assets"
}
if (-not (Test-Path $assetsDir)) {
    throw 'Assets\ khong tim thay!'
}

Get-ChildItem "$assetsDir\css\*.css" -ErrorAction SilentlyContinue | ForEach-Object {
    Copy-Item $_.FullName "$RESOURCES\Assets\css\" -Force
    Write-Host "  + Assets\css\$($_.Name)"
}
if (Test-Path "$assetsDir\css\plugins") {
    Get-ChildItem "$assetsDir\css\plugins\*" -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
        $rel = $_.FullName.Replace("$assetsDir\css\plugins\", '')
        $destDir = Join-Path "$RESOURCES\Assets\css\plugins" (Split-Path $rel)
        if (-not (Test-Path $destDir)) { New-Item -ItemType Directory -Path $destDir -Force | Out-Null }
        Copy-Item $_.FullName (Join-Path "$RESOURCES\Assets\css\plugins" $rel) -Force
    }
    Write-Host '  + Assets\css\plugins\*'
}

Get-ChildItem "$assetsDir\js\*.js" -ErrorAction SilentlyContinue | ForEach-Object {
    Copy-Item $_.FullName "$RESOURCES\Assets\js\" -Force
    Write-Host "  + Assets\js\$($_.Name)"
}

if (Test-Path "$assetsDir\js\builder") {
    Get-ChildItem "$assetsDir\js\builder\*" -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
        $rel = $_.FullName.Replace("$assetsDir\js\builder\", '')
        $destDir = Join-Path "$RESOURCES\Assets\js\builder" (Split-Path $rel)
        if (-not (Test-Path $destDir)) { New-Item -ItemType Directory -Path $destDir -Force | Out-Null }
        Copy-Item $_.FullName (Join-Path "$RESOURCES\Assets\js\builder" $rel) -Force
        Write-Host "  + Assets\js\builder\$rel" -ForegroundColor Cyan
    }
}

if (Test-Path "$assetsDir\js\bundles") {
    Get-ChildItem "$assetsDir\js\bundles\*" -File -ErrorAction SilentlyContinue | ForEach-Object {
        Copy-Item $_.FullName "$RESOURCES\Assets\js\bundles\" -Force
        Write-Host "  + Assets\js\bundles\$($_.Name)" -ForegroundColor Magenta
    }
}

if (Test-Path "$assetsDir\js\plugins") {
    Get-ChildItem "$assetsDir\js\plugins\*" -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
        $rel = $_.FullName.Replace("$assetsDir\js\plugins\", '')
        $destDir = Join-Path "$RESOURCES\Assets\js\plugins" (Split-Path $rel)
        if (-not (Test-Path $destDir)) { New-Item -ItemType Directory -Path $destDir -Force | Out-Null }
        Copy-Item $_.FullName (Join-Path "$RESOURCES\Assets\js\plugins" $rel) -Force
    }
    Write-Host '  + Assets\js\plugins\*'
}

if (Test-Path "$assetsDir\js\locales") {
    Get-ChildItem "$assetsDir\js\locales\*" -File -ErrorAction SilentlyContinue | ForEach-Object {
        Copy-Item $_.FullName "$RESOURCES\Assets\js\locales\" -Force
    }
    Write-Host '  + Assets\js\locales\*'
}

# [i18n language packs 2026-07-09] EXPLICIT + ROBUST copy of the 39 locale JSON files
# (+ index.json). These feed BOTH the Languages admin panel (MegaFormApiController.List
# enumerates these folders) AND runtime lazy-loading of non-English locales. The API
# ResolveI18nFolders() probes, in order: Assets/js/i18n, Assets/i18n, Assets/js/builder/i18n,
# Assets/js/bundles/i18n. Previously ONLY builder/i18n rode in via the recursive builder copy
# (which was intermittently dropping the subfolder → a fresh install shipped ZERO languages,
# Languages panel showed only the en-US baseline). Copy to ALL THREE js locations explicitly so
# a locale is found no matter which probe path the host resolves first. Flat folders (40 files).
foreach ($i18nSub in @('i18n', 'builder\i18n', 'bundles\i18n')) {
    $i18nSrc = Join-Path "$assetsDir\js" $i18nSub
    if (Test-Path $i18nSrc) {
        $i18nDst = Join-Path "$RESOURCES\Assets\js" $i18nSub
        New-Item -ItemType Directory -Path $i18nDst -Force | Out-Null
        $n = 0
        Get-ChildItem "$i18nSrc\*.json" -File -ErrorAction SilentlyContinue | ForEach-Object {
            Copy-Item $_.FullName $i18nDst -Force; $n++
        }
        Write-Host "  + Assets\js\$i18nSub\*.json  ($n language files)" -ForegroundColor Green
    }
}

Get-ChildItem "$assetsDir\embed*.html" -ErrorAction SilentlyContinue | ForEach-Object {
    Copy-Item $_.FullName "$RESOURCES\Assets\" -Force
    Write-Host "  + Assets\$($_.Name)"
}

if (Test-Path "$assetsDir\themes") {
    New-Item -ItemType Directory -Path "$RESOURCES\Assets\themes" -Force | Out-Null
    Get-ChildItem "$assetsDir\themes\*" -File -ErrorAction SilentlyContinue | ForEach-Object {
        Copy-Item $_.FullName "$RESOURCES\Assets\themes\" -Force
    }
    Write-Host '  + Assets\themes\*'
}

# [DNN pack 2026-07-08] Runtime dirs the code reads but the script never shipped:
#  - Assets\img (megaform-ai-bear.png + flags/ for phone country picker)
#  - Resources\PromptRecipes + Resources\TemplateGuides (AiToolsController reads
#    ~/DesktopModules/MegaForm/Resources/...)
#  - Templates (BuilderTemplateCatalogService data root — seed the builder gallery)
if (Test-Path "$assetsDir\img") {
    New-Item -ItemType Directory -Path "$RESOURCES\Assets\img" -Force | Out-Null
    $imgSkipped = 0; $imgSkippedBytes = 0
    Get-ChildItem "$assetsDir\img\*" -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
        $rel = $_.FullName.Replace("$assetsDir\img\", '')
        # Template artwork now ships in the gallery's per-template assets zip and is
        # extracted on install, so keep it OUT of the package.
        if ($SLIM_GALLERY -and ($GALLERY_IMG -contains ($rel -replace '\\', '/'))) {
            $imgSkipped++; $imgSkippedBytes += $_.Length; return
        }
        $destDir = Join-Path "$RESOURCES\Assets\img" (Split-Path $rel)
        if ($destDir -and -not (Test-Path $destDir)) { New-Item -ItemType Directory -Path $destDir -Force | Out-Null }
        Copy-Item $_.FullName (Join-Path "$RESOURCES\Assets\img" $rel) -Force
    }
    if ($imgSkipped -gt 0) {
        Write-Host ("  - Assets\img: {0} gallery-hosted image(s) EXCLUDED ({1:N1} MB)" -f $imgSkipped, ($imgSkippedBytes/1MB)) -ForegroundColor Yellow
    }
    Write-Host '  + Assets\img\* (bear + flags)'
}
if (Test-Path "$assetsDir\fonts") {
    New-Item -ItemType Directory -Path "$RESOURCES\Assets\fonts" -Force | Out-Null
    Copy-Item "$assetsDir\fonts\*" "$RESOURCES\Assets\fonts\" -Recurse -Force
    Write-Host '  + Assets\fonts\*'
}
foreach ($resSub in @('PromptRecipes', 'TemplateGuides')) {
    $src = Join-Path $PROJECT_DIR "Resources\$resSub"
    if (Test-Path $src) {
        $dst = Join-Path $RESOURCES "Resources\$resSub"
        New-Item -ItemType Directory -Path $dst -Force | Out-Null
        Copy-Item "$src\*" $dst -Recurse -Force
        Write-Host "  + Resources\$resSub\*"
    }
}
# [QuickStart 2026-07-24] The bundled shelf a fresh install opens with, in two parts:
#   1. Samples\FormTemplates\QuickStart  — 31 FREE starters (premium:false). These are what
#      makes a trial install usable: none of them is locked.
#   2. the BUNDLED premium starters from the gallery source — the paid designs on display.
#      Everything else in that folder is served from the gallery repo instead (SLIM).
# Keep this in step with tools\gallery\sync-bundled-templates.mjs, which composes the SAME
# two parts into the Oqtane payload.
New-Item -ItemType Directory -Path "$RESOURCES\Templates" -Force | Out-Null

$quickSrc = Join-Path $SOLUTION_DIR 'Samples\FormTemplates\QuickStart'
if (Test-Path $quickSrc) {
    $quickCount = 0
    Get-ChildItem "$quickSrc\*.json" -File -ErrorAction SilentlyContinue | ForEach-Object {
        Copy-Item $_.FullName "$RESOURCES\Templates\" -Force; $quickCount++
    }
    Write-Host ("  + Templates: {0} quick-start starter(s) (free, never locked on trial)" -f $quickCount) -ForegroundColor Green
} else {
    # Fail loudly: silently shipping only the premium starters is the "fresh install shows
    # nothing but locked cards" regression this folder exists to prevent.
    throw "Samples\FormTemplates\QuickStart is missing. Run: node tools/gallery/build-quickstart.mjs"
}

$tplSrc = Join-Path $SOLUTION_DIR 'Samples\FormTemplates\Premium\DONEE'
if (Test-Path $tplSrc) {
    if ($SLIM_GALLERY) {
        # Gallery-hosted templates are downloaded on demand (Template Gallery -> Browse
        # online) on licensed installs, so they no longer ship in the package.
        if (-not $GALLERY_KEEP -or $GALLERY_KEEP.Count -eq 0) {
            throw "gallery-exclude.json has no bundledFiles. Re-run: node tools/gallery/build-gallery.mjs --out <gallery-repo>"
        }
        $tplKept = 0; $tplSkipped = 0; $tplSkippedBytes = 0
        Get-ChildItem "$tplSrc\*" -File -ErrorAction SilentlyContinue | ForEach-Object {
            if ($GALLERY_KEEP -notcontains $_.Name) { $tplSkipped++; $tplSkippedBytes += $_.Length; return }
            Copy-Item $_.FullName "$RESOURCES\Templates\" -Force; $tplKept++
        }
        if ($tplKept -ne $GALLERY_KEEP.Count) {
            throw "Expected $($GALLERY_KEEP.Count) bundled premium starter(s) but copied $tplKept. Source folder and gallery-exclude.json disagree."
        }
        Write-Host ("  - Templates: {0} non-bundled template(s) EXCLUDED ({1:N2} MB), {2} premium starter(s) kept" -f $tplSkipped, ($tplSkippedBytes/1MB), $tplKept) -ForegroundColor Yellow
    } else {
        Copy-Item "$tplSrc\*" "$RESOURCES\Templates\" -Recurse -Force
        Write-Host '  + Templates\* (full premium set — KeepGalleryContent)'
    }
}

$samplesDir = "$SOLUTION_DIR\Samples"
if (-not (Test-Path $samplesDir)) { $samplesDir = "$PROJECT_DIR\Samples" }
if (Test-Path $samplesDir) {
    Copy-Item "$samplesDir\*" "$RESOURCES\Samples\" -Force -ErrorAction SilentlyContinue
    Write-Host '  + Samples\*'
}

if ($Trial) {
    Write-Host '  - license.lic OMITTED (TRIAL edition: install runs unlicensed)' -ForegroundColor Yellow
}
elseif (Test-Path "$PROJECT_DIR\license.lic") {
    Copy-Item "$PROJECT_DIR\license.lic" "$RESOURCES\license.lic" -Force
    Write-Host '  + license.lic (PRODUCTION edition)'
}

Write-Host ''
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\bundles\megaform-builder.js') -Label 'Packaged builder bundle'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\megaform-builder-loader.js') -Label 'Packaged builder loader'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\plugins\megaform-widget-qrcode.js') -Label 'Packaged QRCode plugin'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\megaform-dashboard.js') -Label 'Packaged dashboard bundle'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\megaform-workflow-reactflow.js') -Label 'Packaged workflow canvas bundle'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\react.production.min.js') -Label 'Packaged React runtime'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\react-dom.production.min.js') -Label 'Packaged ReactDOM runtime'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\reactflow.min.js') -Label 'Packaged ReactFlow runtime'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\reactflow.min.css') -Label 'Packaged ReactFlow CSS'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\i18n\index.json') -Label 'Packaged i18n locale index'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\i18n\en-US.json') -Label 'Packaged English locale'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\builder\i18n\vi-VN.json') -Label 'Packaged Vietnamese locale'
# Canonical Assets/js/i18n (MegaFormApiController.List probes this FIRST) — guard the explicit copy.
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\i18n\index.json') -Label 'Packaged i18n (js/i18n) index'
Assert-RequiredFile -PathToCheck (Join-Path $RESOURCES 'Assets\js\i18n\fr-FR.json') -Label 'Packaged i18n (js/i18n) French'
$__i18nCount = (Get-ChildItem (Join-Path $RESOURCES 'Assets\js\i18n\*.json') -File -ErrorAction SilentlyContinue | Measure-Object).Count
if ($__i18nCount -lt 39) { throw "Thieu language packs: chi co $__i18nCount/40 file trong Assets\js\i18n (expected 39 locales + index.json)" }
Write-Host "  [OK] Language packs: $__i18nCount files in Assets\js\i18n" -ForegroundColor Green
Write-Host ''

# ============================================================
#  4. Kiem tra Resources
# ============================================================
Write-Host '[4/7] Kiem tra Resources...' -ForegroundColor Yellow
$allRes = Get-ChildItem $RESOURCES -Recurse -File
Write-Host "  Tong files: $($allRes.Count)" -ForegroundColor Green
Write-Host ''

# ============================================================
#  5. Tao Resources.zip + Install ZIP
# ============================================================
Write-Host '[5/7] Tao Resources.zip...' -ForegroundColor Yellow

Add-Type -AssemblyName System.IO.Compression.FileSystem

$resourcesZip = Join-Path $STAGING 'Resources.zip'
if (Test-Path $resourcesZip) { Remove-Item $resourcesZip -Force }
[System.IO.Compression.ZipFile]::CreateFromDirectory($RESOURCES, $resourcesZip, [System.IO.Compression.CompressionLevel]::Optimal, $false)
Write-Host '  + Resources.zip [OK]' -ForegroundColor Green
Write-Host ''

Write-Host '[6/7] Tao Install Package...' -ForegroundColor Yellow

if (Test-Path $OUTPUT_ZIP) { Remove-Item $OUTPUT_ZIP -Force }

$zip = [System.IO.Compression.ZipFile]::Open($OUTPUT_ZIP, 'Create')

@('MegaForm.dnn', 'License.txt', 'ReleaseNotes.txt', 'icon.gif', 'Resources.zip') | ForEach-Object {
    $fp = Join-Path $STAGING $_
    if (Test-Path $fp) {
        [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $fp, $_) | Out-Null
    }
}

Get-ChildItem "$STAGING\bin" -File | ForEach-Object {
    [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $_.FullName, "bin/$($_.Name)") | Out-Null
}

Get-ChildItem "$STAGING\SqlScripts" -File | ForEach-Object {
    [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $_.FullName, "SqlScripts/$($_.Name)") | Out-Null
}

$zip.Dispose()

# ============================================================
#  7. Don dep + Ket qua
# ============================================================
Write-Host '[7/7] Don dep...' -ForegroundColor Yellow
Remove-Item $STAGING -Recurse -Force

$zipSize = [math]::Round((Get-Item $OUTPUT_ZIP).Length / 1KB, 1)
Write-Host ''
Write-Host '============================================================' -ForegroundColor Green
Write-Host '  HOAN THANH!' -ForegroundColor Green
Write-Host '============================================================' -ForegroundColor Green
Write-Host ''
Write-Host "  Edition: $EDITION $(if ($Trial) { '(no license.lic -> trial caps apply)' } else { '(license.lic=production -> unlimited)' })" -ForegroundColor $(if ($Trial) { 'Yellow' } else { 'Green' })
Write-Host "  Gallery: $(if ($SLIM_GALLERY) { "SLIM - $($GALLERY_TPL.Count) templates + $($GALLERY_IMG.Count) images served from the gallery repo" } else { 'FULL - templates + artwork bundled in the package' })" -ForegroundColor $(if ($SLIM_GALLERY) { 'Cyan' } else { 'Gray' })
Write-Host "  File: $OUTPUT_ZIP" -ForegroundColor White
Write-Host "  Size: ${zipSize} KB" -ForegroundColor White
Write-Host ''
Write-Host '  Package chua:' -ForegroundColor Gray
Write-Host "    MegaForm.dnn               (manifest v$VERSION)" -ForegroundColor Gray
Write-Host '    bin\MegaForm.DNN.dll       (DNN module)' -ForegroundColor Cyan
Write-Host '    bin\MegaForm.Core.dll      (Core shared library)' -ForegroundColor Cyan
Write-Host '    SqlScripts\*.sql' -ForegroundColor Gray
Write-Host '    Resources.zip              (Views + Assets)' -ForegroundColor Gray
Write-Host ''
Write-Host '  Cai dat: DNN -> Host -> Extensions -> Install Extension' -ForegroundColor Yellow
Write-Host ''
if (-not $NoPause) {
    Read-Host 'Nhan Enter de thoat'
}
