/**
 * widget-catalog.gen.ts — AUTO-GENERATED by scripts/build-widget-catalog.cjs (v20260527-05).
 * Do not edit by hand. Regenerate via:
 *   node scripts/build-widget-catalog.cjs
 * Total entries: 52
 */

export interface CatalogEntryProp { key: string; type: string; hasDefault: boolean; }
export interface CatalogEntry { type: string; label: string; icon: string; category: string; kind: 'field' | 'widget'; properties: CatalogEntryProp[]; notes?: string; sourceFile?: string; }

export const WIDGET_CATALOG: CatalogEntry[] = [
  {
    "type": "Text",
    "label": "Short Text",
    "icon": "fa-font",
    "category": "hidden",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "Textarea",
    "label": "Long Text",
    "icon": "fa-align-left",
    "category": "hidden",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "Email",
    "label": "Email",
    "icon": "fa-envelope",
    "category": "hidden",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "Number",
    "label": "Number",
    "icon": "fa-hashtag",
    "category": "hidden",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "Date",
    "label": "Date Picker",
    "icon": "fa-calendar-alt",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "Phone",
    "label": "Phone",
    "icon": "fa-phone",
    "category": "hidden",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "Composite",
    "label": "Input",
    "icon": "fa-object-group",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "TermsPrivacy",
    "label": "Terms & Privacy",
    "icon": "fa-shield-alt",
    "category": "widgets",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "Select",
    "label": "Dropdown",
    "icon": "fa-caret-square-down",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": "Supports options[] (label/value) for static or SQL-source dropdowns."
  },
  {
    "type": "MultiSelect",
    "label": "MultiSelect",
    "icon": "fa-tags",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": "Supports options[] (label/value) for static or SQL-source dropdowns."
  },
  {
    "type": "Radio",
    "label": "Single Choice",
    "icon": "fa-dot-circle",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": "Supports options[] (label/value) for static or SQL-source dropdowns."
  },
  {
    "type": "Checkbox",
    "label": "Multiple Choice",
    "icon": "fa-check-square",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": "Supports options[] (label/value) for static or SQL-source dropdowns."
  },
  {
    "type": "Chips",
    "label": "Chips",
    "icon": "fa-tags",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": "Supports options[] (label/value) for static or SQL-source dropdowns."
  },
  {
    "type": "Cards",
    "label": "Choice Cards",
    "icon": "fa-grip",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": "Supports options[] (label/value) for static or SQL-source dropdowns."
  },
  {
    "type": "File",
    "label": "File Upload",
    "icon": "fa-paperclip",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "Url",
    "label": "Website",
    "icon": "fa-link",
    "category": "hidden",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "Rating",
    "label": "Rating",
    "icon": "fa-star",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "Signature",
    "label": "Signature",
    "icon": "fa-signature",
    "category": "basic",
    "kind": "widget",
    "properties": [
      {
        "key": "penColor",
        "type": "color",
        "hasDefault": true
      },
      {
        "key": "penWidth",
        "type": "number",
        "hasDefault": true
      },
      {
        "key": "bgColor",
        "type": "color",
        "hasDefault": true
      },
      {
        "key": "height",
        "type": "number",
        "hasDefault": true
      },
      {
        "key": "placeholderText",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "clearText",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "undoText",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "showTimestamp",
        "type": "checkbox",
        "hasDefault": true
      },
      {
        "key": "typedMode",
        "type": "checkbox",
        "hasDefault": true
      }
    ],
    "notes": "",
    "sourceFile": "src/widgets/plugins/megaform-widget-signature.ts"
  },
  {
    "type": "RichText",
    "label": "Rich Text",
    "icon": "fa-align-left",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "UniqueId",
    "label": "Unique ID",
    "icon": "fa-fingerprint",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "Captcha",
    "label": "CAPTCHA",
    "icon": "fa-shield-alt",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "MultiColumnCombo",
    "label": "Multi-Column Combo",
    "icon": "fa-table",
    "category": "basic",
    "kind": "widget",
    "properties": [
      {
        "key": "dataSource",
        "type": "select",
        "hasDefault": false
      },
      {
        "key": "displayKey",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "valueKey",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "columns",
        "type": "textarea",
        "hasDefault": true
      },
      {
        "key": "options",
        "type": "textarea",
        "hasDefault": true
      },
      {
        "key": "placeholder",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "searchable",
        "type": "checkbox",
        "hasDefault": true
      },
      {
        "key": "searchPlaceholder",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "masterQuery",
        "type": "textarea",
        "hasDefault": true
      },
      {
        "key": "connectionKey",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "queryDependsOn",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "maxRows",
        "type": "number",
        "hasDefault": true
      }
    ],
    "notes": "",
    "sourceFile": "src/widgets/plugins/megaform-widget-multicolumn-combo.ts"
  },
  {
    "type": "Row",
    "label": "Row / Columns",
    "icon": "fa-columns",
    "category": "layout",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "FlexGrid",
    "label": "Flex Grid (12-col)",
    "icon": "fa-th",
    "category": "layout",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "Html",
    "label": "HTML Block",
    "icon": "fa-code",
    "category": "layout",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "Section",
    "label": "Section Break",
    "icon": "fa-minus",
    "category": "layout",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "Hidden",
    "label": "Hidden Field",
    "icon": "fa-eye-slash",
    "category": "layout",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "StripePayment",
    "label": "Stripe Payment",
    "icon": "fa-credit-card",
    "category": "plugins",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "PayPalPayment",
    "label": "PayPal Payment",
    "icon": "fa-paypal",
    "category": "plugins",
    "kind": "field",
    "properties": [],
    "notes": ""
  },
  {
    "type": "CompositePhone",
    "label": "Phone Number",
    "icon": "fa-phone",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": "Composite preset tile — emit as {type:'Composite', widgetProps:{preset:'phone'}}. The alias 'CompositePhone' is rewritten to Composite+preset on save."
  },
  {
    "type": "CompositeName",
    "label": "Full Name",
    "icon": "fa-user",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": "Composite preset tile — emit as {type:'Composite', widgetProps:{preset:'name'}}. The alias 'CompositeName' is rewritten to Composite+preset on save."
  },
  {
    "type": "CompositeNamePlus",
    "label": "Full Name + Prefix/Suffix",
    "icon": "fa-user-tag",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": "Composite preset tile — emit as {type:'Composite', widgetProps:{preset:'name_plus'}}. The alias 'CompositeNamePlus' is rewritten to Composite+preset on save."
  },
  {
    "type": "CompositeAddress",
    "label": "Address",
    "icon": "fa-map-marker-alt",
    "category": "layout",
    "kind": "field",
    "properties": [],
    "notes": "Composite preset tile — emit as {type:'Composite', widgetProps:{preset:'address'}}. The alias 'CompositeAddress' is rewritten to Composite+preset on save."
  },
  {
    "type": "CompositeSsn",
    "label": "SSN",
    "icon": "fa-id-card",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": "Composite preset tile — emit as {type:'Composite', widgetProps:{preset:'ssn'}}. The alias 'CompositeSsn' is rewritten to Composite+preset on save."
  },
  {
    "type": "CompositeDob",
    "label": "Date of Birth",
    "icon": "fa-birthday-cake",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": "Composite preset tile — emit as {type:'Composite', widgetProps:{preset:'dob'}}. The alias 'CompositeDob' is rewritten to Composite+preset on save."
  },
  {
    "type": "CompositeTime",
    "label": "Time",
    "icon": "fa-clock",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": "Composite preset tile — emit as {type:'Composite', widgetProps:{preset:'time'}}. The alias 'CompositeTime' is rewritten to Composite+preset on save."
  },
  {
    "type": "CompositeEmailConfirm",
    "label": "Email + Confirm",
    "icon": "fa-envelope",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": "Composite preset tile — emit as {type:'Composite', widgetProps:{preset:'email_confirm'}}. The alias 'CompositeEmailConfirm' is rewritten to Composite+preset on save."
  },
  {
    "type": "CompositePasswordConfirm",
    "label": "Password + Confirm",
    "icon": "fa-lock",
    "category": "basic",
    "kind": "field",
    "properties": [],
    "notes": "Composite preset tile — emit as {type:'Composite', widgetProps:{preset:'password_confirm'}}. The alias 'CompositePasswordConfirm' is rewritten to Composite+preset on save."
  },
  {
    "type": "CompositeDateRange",
    "label": "Date Range",
    "icon": "fa-calendar-week",
    "category": "layout",
    "kind": "field",
    "properties": [],
    "notes": "Composite preset tile — emit as {type:'Composite', widgetProps:{preset:'date_range'}}. The alias 'CompositeDateRange' is rewritten to Composite+preset on save."
  },
  {
    "type": "CompositeMoney",
    "label": "Money / Amount",
    "icon": "fa-money-bill-wave",
    "category": "layout",
    "kind": "field",
    "properties": [],
    "notes": "Composite preset tile — emit as {type:'Composite', widgetProps:{preset:'money'}}. The alias 'CompositeMoney' is rewritten to Composite+preset on save."
  },
  {
    "type": "CompositeMeasurement",
    "label": "Measurement",
    "icon": "fa-ruler-combined",
    "category": "layout",
    "kind": "field",
    "properties": [],
    "notes": "Composite preset tile — emit as {type:'Composite', widgetProps:{preset:'measurement'}}. The alias 'CompositeMeasurement' is rewritten to Composite+preset on save."
  },
  {
    "type": "CompositePriceRange",
    "label": "Price Range",
    "icon": "fa-tags",
    "category": "layout",
    "kind": "field",
    "properties": [],
    "notes": "Composite preset tile — emit as {type:'Composite', widgetProps:{preset:'price_range'}}. The alias 'CompositePriceRange' is rewritten to Composite+preset on save."
  },
  {
    "type": "CompositeFullContact",
    "label": "Contact Block",
    "icon": "fa-address-card",
    "category": "layout",
    "kind": "field",
    "properties": [],
    "notes": "Composite preset tile — emit as {type:'Composite', widgetProps:{preset:'full_contact'}}. The alias 'CompositeFullContact' is rewritten to Composite+preset on save."
  },
  {
    "type": "ContentSlider",
    "label": "Content Slider • ",
    "icon": "fa-images",
    "category": "widgets",
    "kind": "widget",
    "properties": [],
    "sourceFile": "src/widgets/plugins/megaform-widget-content-slider.ts"
  },
  {
    "type": "DataRepeater",
    "label": "Data Repeater",
    "icon": "fa-database",
    "category": "advanced",
    "kind": "widget",
    "properties": [],
    "sourceFile": "src/widgets/plugins/megaform-widget-data-repeater.ts"
  },
  {
    "type": "DataGrid",
    "label": "Data Grid (Master-Detail)",
    "icon": "fa-table",
    "category": "advanced",
    "kind": "widget",
    "properties": [
      {
        "key": "useSql",
        "type": "checkbox",
        "hasDefault": true
      },
      {
        "key": "connectionKey",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "masterQuery",
        "type": "textarea",
        "hasDefault": true
      },
      {
        "key": "queryDependsOn",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "pageSize",
        "type": "number",
        "hasDefault": true
      },
      {
        "key": "tableName",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "parentKeyColumn",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "columns",
        "type": "text",
        "hasDefault": false
      },
      {
        "key": "displayTemplate",
        "type": "select",
        "hasDefault": false
      },
      {
        "key": "imageColumn",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "titleColumn",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "subtitleColumn",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "editMode",
        "type": "select",
        "hasDefault": false
      },
      {
        "key": "allowAdd",
        "type": "checkbox",
        "hasDefault": true
      },
      {
        "key": "allowDelete",
        "type": "checkbox",
        "hasDefault": true
      },
      {
        "key": "stickyHeader",
        "type": "checkbox",
        "hasDefault": true
      },
      {
        "key": "rowHeight",
        "type": "select",
        "hasDefault": false
      },
      {
        "key": "minRows",
        "type": "number",
        "hasDefault": true
      },
      {
        "key": "maxRows",
        "type": "number",
        "hasDefault": true
      },
      {
        "key": "totalField",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "totalFormula",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "emptyMessage",
        "type": "text",
        "hasDefault": true
      }
    ],
    "sourceFile": "src/widgets/plugins/megaform-widget-datagrid.ts"
  },
  {
    "type": "DynamicLabel",
    "label": "Dynamic Label",
    "icon": "fa-table-cells",
    "category": "advanced",
    "kind": "widget",
    "properties": [],
    "sourceFile": "src/widgets/plugins/megaform-widget-dynamic-label.ts"
  },
  {
    "type": "GolfScorecard",
    "label": "GolfScorecard",
    "icon": "",
    "category": "advanced",
    "kind": "widget",
    "properties": [],
    "sourceFile": "src/widgets/plugins/megaform-widget-golf-scorecard.ts"
  },
  {
    "type": "Map",
    "label": "Map (OSM)",
    "icon": "fa-map-location-dot",
    "category": "widgets",
    "kind": "widget",
    "properties": [],
    "sourceFile": "src/widgets/plugins/megaform-widget-map.ts"
  },
  {
    "type": "QRCode",
    "label": "QR Code • ",
    "icon": "fa-qrcode",
    "category": "widgets",
    "kind": "widget",
    "properties": [],
    "sourceFile": "src/widgets/plugins/megaform-widget-qrcode.ts"
  },
  {
    "type": "Razor",
    "label": "Razor Widget",
    "icon": "fa-code",
    "category": "advanced",
    "kind": "widget",
    "properties": [
      {
        "key": "templateName",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "parameters",
        "type": "textarea",
        "hasDefault": true
      },
      {
        "key": "useSql",
        "type": "checkbox",
        "hasDefault": true
      },
      {
        "key": "connectionKey",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "masterQuery",
        "type": "textarea",
        "hasDefault": true
      },
      {
        "key": "queryDependsOn",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "dependsOn",
        "type": "text",
        "hasDefault": true
      },
      {
        "key": "reloadOnParamChange",
        "type": "checkbox",
        "hasDefault": true
      },
      {
        "key": "cssClass",
        "type": "text",
        "hasDefault": true
      }
    ],
    "sourceFile": "src/widgets/plugins/megaform-widget-razor.ts"
  },
  {
    "type": "UserTemplate",
    "label": "User Template (BYOM)",
    "icon": "fas fa-puzzle-piece",
    "category": "Layout",
    "kind": "widget",
    "properties": [
      {
        "key": "templateName",
        "type": "select",
        "hasDefault": true
      },
      {
        "key": "showInError",
        "type": "checkbox",
        "hasDefault": true
      }
    ],
    "sourceFile": "src/widgets/plugins/megaform-widget-user-template.ts"
  }
];

export function summarizeCatalogForSystemPrompt(): string {
  return WIDGET_CATALOG.map((e) => {
    const propList = e.properties && e.properties.length
      ? '\n  Properties: ' + e.properties.map((p) => p.key + '(' + p.type + ')').join(', ')
      : '';
    const noteSuffix = e.notes ? '\n  Note: ' + e.notes : '';
    return '- ' + e.type + ' (' + e.kind + ', ' + e.category + '): ' + e.label + propList + noteSuffix;
  }).join('\n');
}
