import type { PresetEntry, RepeaterDraft } from './types';

export const STARTER_PRESETS: PresetEntry[] = [
  {
    key: 'dnn-structure',
    label: 'DNN structure explorer',
    description: 'Portal list -> page grid -> page modules, using the current DNN database structure.',
    preset: {
      dataSource: 'sql',
      connectionKey: 'DashboardDatabase',
      databaseType: 'SqlServer',
      masterQuery: [
        'SELECT',
        '  p.PortalID,',
        "  COALESCE(NULLIF(pa.HTTPAlias, ''), CONCAT('Portal ', p.PortalID)) AS PortalLabel,",
        "  COALESCE(NULLIF(pa.HTTPAlias, ''), '(no primary alias)') AS PrimaryAlias,",
        '  p.HomeDirectory,',
        '  pageStats.PageCount,',
        '  moduleStats.ModuleCount',
        'FROM dbo.Portals p',
        'OUTER APPLY (',
        '  SELECT TOP 1 HTTPAlias',
        '  FROM dbo.PortalAlias',
        '  WHERE PortalID = p.PortalID',
        '  ORDER BY IsPrimary DESC, PortalAliasID',
        ') pa',
        'OUTER APPLY (',
        '  SELECT COUNT(*) AS PageCount',
        '  FROM dbo.Tabs t',
        '  WHERE t.PortalID = p.PortalID AND t.IsDeleted = 0',
        ') pageStats',
        'OUTER APPLY (',
        '  SELECT COUNT(*) AS ModuleCount',
        '  FROM dbo.TabModules tm',
        '  JOIN dbo.Modules m ON m.ModuleID = tm.ModuleID',
        '  WHERE m.PortalID = p.PortalID AND tm.IsDeleted = 0 AND ISNULL(m.IsDeleted, 0) = 0',
        ') moduleStats',
        'ORDER BY p.PortalID',
      ].join('\n'),
      masterTemplate: [
        "<article class='mfdr-row' data-row-index='{#index}' style='display:grid;grid-template-columns:1.4fr .7fr .7fr;gap:14px;padding:14px 16px;margin:0 0 12px;border:1px solid #dbe4f0;border-radius:14px;background:#fff;'>",
        '  <div>',
        "    <div style='font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:#64748b;font-weight:700;'>Portal #{PortalID}</div>",
        "    <div style='margin-top:6px;font-size:18px;font-weight:700;color:#0f172a;'>{PortalLabel|link:detail:PortalID}</div>",
        "    <div style='margin-top:4px;font-size:12px;color:#475569;'>Primary alias: {PrimaryAlias}</div>",
        "    <div style='margin-top:4px;font-size:12px;color:#94a3b8;'>Home directory: {HomeDirectory}</div>",
        '  </div>',
        "  <div style='display:flex;flex-direction:column;justify-content:center;padding:10px 12px;border-radius:12px;background:#f8fafc;'>",
        "    <div style='font-size:11px;letter-spacing:.06em;text-transform:uppercase;color:#64748b;font-weight:700;'>Pages</div>",
        "    <div style='margin-top:6px;font-size:24px;font-weight:700;color:#4338ca;'>{PageCount}</div>",
        '  </div>',
        "  <div style='display:flex;flex-direction:column;justify-content:center;padding:10px 12px;border-radius:12px;background:#f8fafc;'>",
        "    <div style='font-size:11px;letter-spacing:.06em;text-transform:uppercase;color:#64748b;font-weight:700;'>Modules</div>",
        "    <div style='margin-top:6px;font-size:24px;font-weight:700;color:#0f766e;'>{ModuleCount}</div>",
        '  </div>',
        '</article>',
      ].join('\n'),
      detail1TriggerCol: 'PortalLabel',
      detail1Placement: 'after',
      detail1Query: [
        'SELECT',
        '  t.TabID,',
        '  t.PortalID,',
        "  COALESCE(NULLIF(t.Title, ''), t.TabName) AS PageTitle,",
        '  t.TabName,',
        '  t.TabPath,',
        '  t.Level,',
        "  CASE WHEN t.IsVisible = 1 THEN 'Visible' ELSE 'Hidden' END AS Visibility,",
        '  moduleStats.ModuleCount',
        'FROM dbo.Tabs t',
        'OUTER APPLY (',
        '  SELECT COUNT(*) AS ModuleCount',
        '  FROM dbo.TabModules tm',
        '  JOIN dbo.Modules m ON m.ModuleID = tm.ModuleID',
        '  WHERE tm.TabID = t.TabID AND tm.IsDeleted = 0 AND ISNULL(m.IsDeleted, 0) = 0',
        ') moduleStats',
        'WHERE t.PortalID = TRY_CONVERT(int, :parentId)',
        '  AND t.IsDeleted = 0',
        'ORDER BY t.Level, t.TabOrder, t.TabID',
      ].join('\n'),
      detail1Template: [
        "<article class='mfdr-row' data-row-index='{#index}' style='display:grid;grid-template-columns:1.5fr .8fr .7fr;gap:14px;padding:14px;margin:0 0 10px;border:1px solid #e2e8f0;border-radius:12px;background:#fbfdff;'>",
        '  <div>',
        "    <div style='font-size:16px;font-weight:700;color:#0f172a;'>{PageTitle|link:detail:TabID}</div>",
        "    <div style='margin-top:4px;font-size:12px;color:#64748b;'>{TabPath}</div>",
        "    <div style='margin-top:4px;font-size:12px;color:#94a3b8;'>Tab name: {TabName}</div>",
        '  </div>',
        "  <div style='display:flex;flex-direction:column;justify-content:center;'>",
        "    <div style='font-size:11px;letter-spacing:.06em;text-transform:uppercase;color:#64748b;font-weight:700;'>Visibility / Level</div>",
        "    <div style='margin-top:6px;font-size:14px;font-weight:600;color:#334155;'>{Visibility} / L{Level}</div>",
        '  </div>',
        "  <div style='display:flex;flex-direction:column;justify-content:center;padding:10px 12px;border-radius:10px;background:#f8fafc;'>",
        "    <div style='font-size:11px;letter-spacing:.06em;text-transform:uppercase;color:#64748b;font-weight:700;'>Modules on page</div>",
        "    <div style='margin-top:6px;font-size:20px;font-weight:700;color:#2563eb;'>{ModuleCount}</div>",
        '  </div>',
        '</article>',
      ].join('\n'),
      detail2TriggerCol: 'PageTitle',
      detail2Placement: 'after',
      detail2Query: [
        'SELECT',
        '  tm.TabModuleID,',
        '  tm.ModuleOrder,',
        "  COALESCE(NULLIF(tm.ModuleTitle, ''), dm.FriendlyName, dm.ModuleName, CONCAT('Module #', tm.ModuleID)) AS ModuleTitle,",
        '  tm.PaneName,',
        '  dm.ModuleName,',
        '  dm.FriendlyName,',
        '  tm.ModuleID',
        'FROM dbo.TabModules tm',
        'JOIN dbo.Modules m ON m.ModuleID = tm.ModuleID',
        'LEFT JOIN dbo.ModuleDefinitions md ON md.ModuleDefID = m.ModuleDefID',
        'LEFT JOIN dbo.DesktopModules dm ON dm.DesktopModuleID = md.DesktopModuleID',
        'WHERE tm.TabID = TRY_CONVERT(int, :parentId)',
        '  AND tm.IsDeleted = 0',
        '  AND ISNULL(m.IsDeleted, 0) = 0',
        'ORDER BY tm.ModuleOrder, tm.TabModuleID',
      ].join('\n'),
      detail2Template: [
        "<article class='mfdr-row' data-row-index='{#index}' style='display:grid;grid-template-columns:1.5fr .8fr .8fr;gap:14px;padding:12px 14px;margin:0 0 8px;border:1px solid #e2e8f0;border-radius:12px;background:#fff;'>",
        '  <div>',
        "    <div style='font-size:15px;font-weight:700;color:#0f172a;'>{ModuleTitle}</div>",
        "    <div style='margin-top:4px;font-size:12px;color:#64748b;'>Definition: {FriendlyName}</div>",
        "    <div style='margin-top:4px;font-size:12px;color:#94a3b8;'>Code: {ModuleName}</div>",
        '  </div>',
        "  <div style='display:flex;flex-direction:column;justify-content:center;'>",
        "    <div style='font-size:11px;letter-spacing:.06em;text-transform:uppercase;color:#64748b;font-weight:700;'>Pane</div>",
        "    <div style='margin-top:6px;font-size:14px;font-weight:600;color:#334155;'>{PaneName}</div>",
        '  </div>',
        "  <div style='display:flex;flex-direction:column;justify-content:center;'>",
        "    <div style='font-size:11px;letter-spacing:.06em;text-transform:uppercase;color:#64748b;font-weight:700;'>Order / ID</div>",
        "    <div style='margin-top:6px;font-size:14px;font-weight:600;color:#334155;'>#{ModuleOrder} / {ModuleID}</div>",
        '  </div>',
        '</article>',
      ].join('\n'),
      pageSize: 10,
      maxRows: 500,
      emptyMessage: 'No DNN structure rows found.',
      cssClass: 'mfdr-dnn-structure',
      queryDependsOn: '',
      reloadOnParamChange: true,
    },
  },
  {
    key: 'master-only',
    label: 'Master query only',
    description: 'Simple table or stored procedure result with paging only.',
    preset: {
      dataSource: 'sql',
      connectionKey: 'DashboardDatabase',
      databaseType: 'SqlServer',
      masterQuery: 'SELECT TOP 50 cardid, EventDate, DisplayName, Gross, Net\nFROM Golf.dbo.CardResultNew\nORDER BY EventDate DESC',
      pageSize: 50,
      maxRows: 1000,
      emptyMessage: 'No data found.',
      cssClass: 'mfdr-master-only',
    },
  },
  {
    key: 'master-detail-drilldown',
    label: 'Master + Detail drill-down',
    description: 'Click a master column to open level-1 detail inline.',
    preset: {
      dataSource: 'sql',
      connectionKey: 'DashboardDatabase',
      databaseType: 'SqlServer',
      masterQuery: 'SELECT cardid AS id, DisplayName AS Player, Gross, Net\nFROM Golf.dbo.CardResultNew\nWHERE EventDate = (SELECT MAX(EventDate) FROM Golf.dbo.CardResultNew)\nORDER BY Net',
      detail1TriggerCol: 'Player',
      detail1Query: 'SELECT * FROM Golf.dbo.CardResultNew\nWHERE LTRIM(RTRIM(DisplayName)) = :parentId\nORDER BY EventDate DESC',
      detail1Placement: 'after',
      pageSize: 50,
      maxRows: 1000,
      emptyMessage: 'No data.',
      cssClass: 'mfdr-master-detail',
      golfMode: true,
    },
  },
  {
    key: 'leaderboard-grouped',
    label: 'Leaderboard grouped by Flight',
    description: 'Accordion sections per group, plus level-1 player detail.',
    preset: {
      dataSource: 'sql',
      connectionKey: 'DashboardDatabase',
      databaseType: 'SqlServer',
      masterQuery: "WITH dates AS (\n  SELECT TOP 3 EventDate, ROW_NUMBER() OVER (ORDER BY EventDate DESC) AS rn\n  FROM (SELECT DISTINCT EventDate FROM Golf.dbo.CardResultNew) d\n  ORDER BY EventDate DESC\n)\nSELECT\n  ROW_NUMBER() OVER (ORDER BY SUM(c.Gross) - 216) AS Position,\n  LTRIM(RTRIM(c.DisplayName)) AS PlayerName,\n  CONCAT('Flight ', MIN(c.Flight)) AS Flight,\n  SUM(CASE WHEN d.rn=1 THEN c.Gross END) AS R1,\n  SUM(CASE WHEN d.rn=2 THEN c.Gross END) AS R2,\n  SUM(CASE WHEN d.rn=3 THEN c.Gross END) AS R3,\n  SUM(c.Gross) AS Gross,\n  SUM(c.Net) AS Net\nFROM Golf.dbo.CardResultNew c\nJOIN dates d ON d.EventDate = c.EventDate\nWHERE c.EventNo = 1\nGROUP BY LTRIM(RTRIM(c.DisplayName))\nHAVING SUM(c.Gross) > 0\nORDER BY SUM(c.Gross)",
      groupByCol: 'Flight',
      detail1TriggerCol: 'PlayerName',
      detail1Query: 'SELECT * FROM Golf.dbo.CardResultNew\nWHERE LTRIM(RTRIM(DisplayName)) = :parentId\nORDER BY EventDate DESC',
      detail1Placement: 'after',
      pageSize: 0,
      maxRows: 1000,
      emptyMessage: 'No tournament data.',
      cssClass: 'mfdr-leaderboard',
      golfMode: true,
    },
  },
  {
    key: 'master-with-filter',
    label: 'Master + Filter dropdown',
    description: 'One filter dropdown that reloads the master query.',
    preset: {
      dataSource: 'sql',
      connectionKey: 'DashboardDatabase',
      databaseType: 'SqlServer',
      masterQuery: 'SELECT cardid, EventDate, DisplayName, Gross, Net\nFROM Golf.dbo.CardResultNew\nWHERE Flight = COALESCE(:flight, Flight)\nORDER BY Net',
      filter1Label: 'Flight',
      filter1Param: 'flight',
      filter1Type: 'dropdown',
      filter1Query: 'SELECT DISTINCT Flight FROM Golf.dbo.CardResultNew ORDER BY Flight',
      pageSize: 50,
      maxRows: 1000,
      emptyMessage: 'No data.',
      cssClass: 'mfdr-filtered',
    },
  },
];

export const FEATURED_SAMPLE_PRESET_KEYS = ['leaderboard-grouped', 'dnn-structure'] as const;

export function findPresetByKey(key: string): PresetEntry | null {
  for (const preset of STARTER_PRESETS) {
    if (preset.key === key) return preset;
  }
  return null;
}

export function detectPresetKey(draft: RepeaterDraft): string {
  const current = signature(draft);
  for (const preset of STARTER_PRESETS) {
    if (signature(preset.preset) === current) return preset.key;
  }
  return '';
}

function signature(value: Partial<RepeaterDraft> & Record<string, any>): string {
  return [
    norm(value.dataSource),
    norm(value.connectionKey),
    norm(value.masterQuery).slice(0, 120),
    norm(value.detail1Query).slice(0, 80),
    norm(value.detail1TriggerCol),
    norm(value.filter1Type),
    norm(value.groupByCol),
  ].join('|');
}

function norm(value: any): string {
  return String(value || '').replace(/\s+/g, ' ').trim().toLowerCase();
}
