using System;
using Microsoft.EntityFrameworkCore;

namespace MegaForm.Web.Data
{
    /// <summary>
    /// Idempotent creation of AI Knowledge Base tables for existing MegaForm.Web
    /// databases. New databases get these tables via EF EnsureCreated; this helper
    /// ensures upgrades from earlier Web builds also receive MF_AI_* tables.
    /// </summary>
    public static class AiKnowledgeSchemaBootstrapper
    {
        public static void EnsureAiKnowledgeTables(MegaFormDbContext db)
        {
            EnsureTable(db, "MF_AI_Knowledge", CreateKnowledgeSql(db));
            EnsureTable(db, "MF_AI_Knowledge_History", CreateHistorySql(db));
            EnsureTable(db, "MF_AI_KB_Templates", CreateTemplatesSql(db));
            EnsureTable(db, "MF_AI_KB_Rules", CreateRulesSql(db));
            EnsureTable(db, "MF_AI_KB_Feedback", CreateFeedbackSql(db));
        }

        private static void EnsureTable(MegaFormDbContext db, string tableName, string createSql)
        {
            if (string.IsNullOrWhiteSpace(createSql)) return;
            if (TableExists(db, tableName)) return;
            ExecuteNonQuery(db, createSql);
        }

        private static bool TableExists(MegaFormDbContext db, string tableName)
        {
            var provider = (db.Database.ProviderName ?? string.Empty).ToLowerInvariant();
            var conn = db.Database.GetDbConnection();
            var shouldClose = conn.State != System.Data.ConnectionState.Open;
            if (shouldClose) conn.Open();
            try
            {
                using var cmd = conn.CreateCommand();
                cmd.CommandText = provider.Contains("sqlserver")
                    ? "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE LOWER(TABLE_NAME) = LOWER(@tableName)"
                    : provider.Contains("npgsql")
                        ? "SELECT COUNT(*) FROM information_schema.tables WHERE LOWER(table_name) = LOWER(@tableName)"
                        : provider.Contains("mysql")
                            ? "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = DATABASE() AND LOWER(table_name) = LOWER(@tableName)"
                            : "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND LOWER(name) = LOWER(@tableName)";
                var p = cmd.CreateParameter();
                p.ParameterName = "@tableName";
                p.Value = tableName;
                cmd.Parameters.Add(p);
                return Convert.ToInt32(cmd.ExecuteScalar() ?? 0) > 0;
            }
            finally
            {
                if (shouldClose) conn.Close();
            }
        }

        private static void ExecuteNonQuery(MegaFormDbContext db, string sql)
        {
            var conn = db.Database.GetDbConnection();
            var shouldClose = conn.State != System.Data.ConnectionState.Open;
            if (shouldClose) conn.Open();
            try
            {
                using var cmd = conn.CreateCommand();
                cmd.CommandText = sql;
                cmd.ExecuteNonQuery();
            }
            finally
            {
                if (shouldClose) conn.Close();
            }
        }

        private static string CreateKnowledgeSql(MegaFormDbContext db)
        {
            var p = (db.Database.ProviderName ?? string.Empty).ToLowerInvariant();
            if (p.Contains("sqlserver"))
                return @"
IF OBJECT_ID(N'[MF_AI_Knowledge]', N'U') IS NULL
BEGIN
    CREATE TABLE [MF_AI_Knowledge] (
        [Id] int IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [Slug] nvarchar(160) NOT NULL DEFAULT '',
        [Kind] nvarchar(40) NOT NULL DEFAULT '',
        [Title] nvarchar(200) NOT NULL DEFAULT '',
        [Summary] nvarchar(max) NOT NULL DEFAULT '',
        [Body] nvarchar(max) NOT NULL DEFAULT '',
        [Tags] nvarchar(500) NOT NULL DEFAULT '',
        [Examples] nvarchar(max) NOT NULL DEFAULT '',
        [PortalId] int NULL,
        [Source] nvarchar(40) NOT NULL DEFAULT 'customer',
        [Version] int NOT NULL DEFAULT 1,
        [WidgetType] nvarchar(80) NOT NULL DEFAULT '',
        [Surface] nvarchar(80) NOT NULL DEFAULT '',
        [CreatedByUserId] int NULL,
        [CreatedOnDate] datetime2 NOT NULL,
        [UpdatedByUserId] int NULL,
        [UpdatedOnDate] datetime2 NULL
    );
    CREATE UNIQUE INDEX [IX_MF_AI_Knowledge_Slug_Portal] ON [MF_AI_Knowledge]([Slug], [PortalId]);
    CREATE INDEX [IX_MF_AI_Knowledge_Widget_Surface] ON [MF_AI_Knowledge]([WidgetType], [Surface]);
END";
            if (p.Contains("npgsql"))
                return @"
CREATE TABLE IF NOT EXISTS ""MF_AI_Knowledge"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""Slug"" text NOT NULL DEFAULT '',
    ""Kind"" text NOT NULL DEFAULT '',
    ""Title"" text NOT NULL DEFAULT '',
    ""Summary"" text NOT NULL DEFAULT '',
    ""Body"" text NOT NULL DEFAULT '',
    ""Tags"" text NOT NULL DEFAULT '',
    ""Examples"" text NOT NULL DEFAULT '',
    ""PortalId"" integer NULL,
    ""Source"" text NOT NULL DEFAULT 'customer',
    ""Version"" integer NOT NULL DEFAULT 1,
    ""WidgetType"" text NOT NULL DEFAULT '',
    ""Surface"" text NOT NULL DEFAULT '',
    ""CreatedByUserId"" integer NULL,
    ""CreatedOnDate"" timestamp without time zone NOT NULL,
    ""UpdatedByUserId"" integer NULL,
    ""UpdatedOnDate"" timestamp without time zone NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_MF_AI_Knowledge_Slug_Portal"" ON ""MF_AI_Knowledge""(""Slug"", ""PortalId"");
CREATE INDEX IF NOT EXISTS ""IX_MF_AI_Knowledge_Widget_Surface"" ON ""MF_AI_Knowledge""(""WidgetType"", ""Surface"");";
            if (p.Contains("mysql"))
                return @"
CREATE TABLE IF NOT EXISTS `MF_AI_Knowledge` (
    `Id` int NOT NULL AUTO_INCREMENT,
    `Slug` varchar(160) NOT NULL DEFAULT '',
    `Kind` varchar(40) NOT NULL DEFAULT '',
    `Title` varchar(200) NOT NULL DEFAULT '',
    `Summary` longtext NOT NULL,
    `Body` longtext NOT NULL,
    `Tags` varchar(500) NOT NULL DEFAULT '',
    `Examples` longtext NOT NULL,
    `PortalId` int NULL,
    `Source` varchar(40) NOT NULL DEFAULT 'customer',
    `Version` int NOT NULL DEFAULT 1,
    `WidgetType` varchar(80) NOT NULL DEFAULT '',
    `Surface` varchar(80) NOT NULL DEFAULT '',
    `CreatedByUserId` int NULL,
    `CreatedOnDate` datetime(6) NOT NULL,
    `UpdatedByUserId` int NULL,
    `UpdatedOnDate` datetime(6) NULL,
    PRIMARY KEY (`Id`),
    UNIQUE KEY `IX_MF_AI_Knowledge_Slug_Portal` (`Slug`, `PortalId`),
    KEY `IX_MF_AI_Knowledge_Widget_Surface` (`WidgetType`, `Surface`)
);";
            return @"
CREATE TABLE IF NOT EXISTS MF_AI_Knowledge (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Slug TEXT NOT NULL DEFAULT '',
    Kind TEXT NOT NULL DEFAULT '',
    Title TEXT NOT NULL DEFAULT '',
    Summary TEXT NOT NULL DEFAULT '',
    Body TEXT NOT NULL DEFAULT '',
    Tags TEXT NOT NULL DEFAULT '',
    Examples TEXT NOT NULL DEFAULT '',
    PortalId INTEGER NULL,
    Source TEXT NOT NULL DEFAULT 'customer',
    Version INTEGER NOT NULL DEFAULT 1,
    WidgetType TEXT NOT NULL DEFAULT '',
    Surface TEXT NOT NULL DEFAULT '',
    CreatedByUserId INTEGER NULL,
    CreatedOnDate TEXT NOT NULL,
    UpdatedByUserId INTEGER NULL,
    UpdatedOnDate TEXT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS IX_MF_AI_Knowledge_Slug_Portal ON MF_AI_Knowledge(Slug, PortalId);
CREATE INDEX IF NOT EXISTS IX_MF_AI_Knowledge_Widget_Surface ON MF_AI_Knowledge(WidgetType, Surface);";
        }

        private static string CreateHistorySql(MegaFormDbContext db)
        {
            var p = (db.Database.ProviderName ?? string.Empty).ToLowerInvariant();
            if (p.Contains("sqlserver"))
                return @"
IF OBJECT_ID(N'[MF_AI_Knowledge_History]', N'U') IS NULL
BEGIN
    CREATE TABLE [MF_AI_Knowledge_History] (
        [HistoryId] int IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [KnowledgeId] int NOT NULL DEFAULT 0,
        [Slug] nvarchar(160) NOT NULL DEFAULT '',
        [Kind] nvarchar(40) NOT NULL DEFAULT '',
        [Title] nvarchar(200) NOT NULL DEFAULT '',
        [Summary] nvarchar(max) NOT NULL DEFAULT '',
        [Body] nvarchar(max) NOT NULL DEFAULT '',
        [Tags] nvarchar(500) NOT NULL DEFAULT '',
        [Examples] nvarchar(max) NOT NULL DEFAULT '',
        [Source] nvarchar(40) NOT NULL DEFAULT 'customer',
        [Version] int NOT NULL DEFAULT 1,
        [ChangedByUserId] int NULL,
        [ChangedOnDate] datetime2 NOT NULL,
        [ChangeAction] nvarchar(16) NOT NULL DEFAULT ''
    );
    CREATE INDEX [IX_MF_AI_Knowledge_History_KnowledgeId] ON [MF_AI_Knowledge_History]([KnowledgeId]);
END";
            if (p.Contains("npgsql"))
                return @"
CREATE TABLE IF NOT EXISTS ""MF_AI_Knowledge_History"" (
    ""HistoryId"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""KnowledgeId"" integer NOT NULL DEFAULT 0,
    ""Slug"" text NOT NULL DEFAULT '',
    ""Kind"" text NOT NULL DEFAULT '',
    ""Title"" text NOT NULL DEFAULT '',
    ""Summary"" text NOT NULL DEFAULT '',
    ""Body"" text NOT NULL DEFAULT '',
    ""Tags"" text NOT NULL DEFAULT '',
    ""Examples"" text NOT NULL DEFAULT '',
    ""Source"" text NOT NULL DEFAULT 'customer',
    ""Version"" integer NOT NULL DEFAULT 1,
    ""ChangedByUserId"" integer NULL,
    ""ChangedOnDate"" timestamp without time zone NOT NULL,
    ""ChangeAction"" text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS ""IX_MF_AI_Knowledge_History_KnowledgeId"" ON ""MF_AI_Knowledge_History""(""KnowledgeId"");";
            if (p.Contains("mysql"))
                return @"
CREATE TABLE IF NOT EXISTS `MF_AI_Knowledge_History` (
    `HistoryId` int NOT NULL AUTO_INCREMENT,
    `KnowledgeId` int NOT NULL DEFAULT 0,
    `Slug` varchar(160) NOT NULL DEFAULT '',
    `Kind` varchar(40) NOT NULL DEFAULT '',
    `Title` varchar(200) NOT NULL DEFAULT '',
    `Summary` longtext NOT NULL,
    `Body` longtext NOT NULL,
    `Tags` varchar(500) NOT NULL DEFAULT '',
    `Examples` longtext NOT NULL,
    `Source` varchar(40) NOT NULL DEFAULT 'customer',
    `Version` int NOT NULL DEFAULT 1,
    `ChangedByUserId` int NULL,
    `ChangedOnDate` datetime(6) NOT NULL,
    `ChangeAction` varchar(16) NOT NULL DEFAULT '',
    PRIMARY KEY (`HistoryId`),
    KEY `IX_MF_AI_Knowledge_History_KnowledgeId` (`KnowledgeId`)
);";
            return @"
CREATE TABLE IF NOT EXISTS MF_AI_Knowledge_History (
    HistoryId INTEGER PRIMARY KEY AUTOINCREMENT,
    KnowledgeId INTEGER NOT NULL DEFAULT 0,
    Slug TEXT NOT NULL DEFAULT '',
    Kind TEXT NOT NULL DEFAULT '',
    Title TEXT NOT NULL DEFAULT '',
    Summary TEXT NOT NULL DEFAULT '',
    Body TEXT NOT NULL DEFAULT '',
    Tags TEXT NOT NULL DEFAULT '',
    Examples TEXT NOT NULL DEFAULT '',
    Source TEXT NOT NULL DEFAULT 'customer',
    Version INTEGER NOT NULL DEFAULT 1,
    ChangedByUserId INTEGER NULL,
    ChangedOnDate TEXT NOT NULL,
    ChangeAction TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS IX_MF_AI_Knowledge_History_KnowledgeId ON MF_AI_Knowledge_History(KnowledgeId);";
        }

        private static string CreateTemplatesSql(MegaFormDbContext db)
        {
            var p = (db.Database.ProviderName ?? string.Empty).ToLowerInvariant();
            if (p.Contains("sqlserver"))
                return @"
IF OBJECT_ID(N'[MF_AI_KB_Templates]', N'U') IS NULL
BEGIN
    CREATE TABLE [MF_AI_KB_Templates] (
        [Id] int IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [KnowledgeId] int NOT NULL DEFAULT 0,
        [TemplateKey] nvarchar(80) NOT NULL DEFAULT '',
        [Kind] nvarchar(40) NOT NULL DEFAULT '',
        [Title] nvarchar(200) NOT NULL DEFAULT '',
        [Summary] nvarchar(max) NOT NULL DEFAULT '',
        [Body] nvarchar(max) NOT NULL DEFAULT '',
        [Tags] nvarchar(500) NOT NULL DEFAULT '',
        [Score] int NOT NULL DEFAULT 0,
        [SortOrder] int NOT NULL DEFAULT 100,
        [PortalId] int NULL,
        [Source] nvarchar(40) NOT NULL DEFAULT 'customer',
        [Version] int NOT NULL DEFAULT 1,
        [CreatedByUserId] int NULL,
        [CreatedOnDate] datetime2 NOT NULL,
        [UpdatedByUserId] int NULL,
        [UpdatedOnDate] datetime2 NULL
    );
    CREATE INDEX [IX_MF_AI_KB_Templates_KnowledgeId] ON [MF_AI_KB_Templates]([KnowledgeId]);
    CREATE UNIQUE INDEX [IX_MF_AI_KB_Templates_Key] ON [MF_AI_KB_Templates]([KnowledgeId], [TemplateKey], [PortalId]);
END";
            if (p.Contains("npgsql"))
                return @"
CREATE TABLE IF NOT EXISTS ""MF_AI_KB_Templates"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""KnowledgeId"" integer NOT NULL DEFAULT 0,
    ""TemplateKey"" text NOT NULL DEFAULT '',
    ""Kind"" text NOT NULL DEFAULT '',
    ""Title"" text NOT NULL DEFAULT '',
    ""Summary"" text NOT NULL DEFAULT '',
    ""Body"" text NOT NULL DEFAULT '',
    ""Tags"" text NOT NULL DEFAULT '',
    ""Score"" integer NOT NULL DEFAULT 0,
    ""SortOrder"" integer NOT NULL DEFAULT 100,
    ""PortalId"" integer NULL,
    ""Source"" text NOT NULL DEFAULT 'customer',
    ""Version"" integer NOT NULL DEFAULT 1,
    ""CreatedByUserId"" integer NULL,
    ""CreatedOnDate"" timestamp without time zone NOT NULL,
    ""UpdatedByUserId"" integer NULL,
    ""UpdatedOnDate"" timestamp without time zone NULL
);
CREATE INDEX IF NOT EXISTS ""IX_MF_AI_KB_Templates_KnowledgeId"" ON ""MF_AI_KB_Templates""(""KnowledgeId"");
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_MF_AI_KB_Templates_Key"" ON ""MF_AI_KB_Templates""(""KnowledgeId"", ""TemplateKey"", ""PortalId"");";
            if (p.Contains("mysql"))
                return @"
CREATE TABLE IF NOT EXISTS `MF_AI_KB_Templates` (
    `Id` int NOT NULL AUTO_INCREMENT,
    `KnowledgeId` int NOT NULL DEFAULT 0,
    `TemplateKey` varchar(80) NOT NULL DEFAULT '',
    `Kind` varchar(40) NOT NULL DEFAULT '',
    `Title` varchar(200) NOT NULL DEFAULT '',
    `Summary` longtext NOT NULL,
    `Body` longtext NOT NULL,
    `Tags` varchar(500) NOT NULL DEFAULT '',
    `Score` int NOT NULL DEFAULT 0,
    `SortOrder` int NOT NULL DEFAULT 100,
    `PortalId` int NULL,
    `Source` varchar(40) NOT NULL DEFAULT 'customer',
    `Version` int NOT NULL DEFAULT 1,
    `CreatedByUserId` int NULL,
    `CreatedOnDate` datetime(6) NOT NULL,
    `UpdatedByUserId` int NULL,
    `UpdatedOnDate` datetime(6) NULL,
    PRIMARY KEY (`Id`),
    KEY `IX_MF_AI_KB_Templates_KnowledgeId` (`KnowledgeId`),
    UNIQUE KEY `IX_MF_AI_KB_Templates_Key` (`KnowledgeId`, `TemplateKey`, `PortalId`)
);";
            return @"
CREATE TABLE IF NOT EXISTS MF_AI_KB_Templates (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    KnowledgeId INTEGER NOT NULL DEFAULT 0,
    TemplateKey TEXT NOT NULL DEFAULT '',
    Kind TEXT NOT NULL DEFAULT '',
    Title TEXT NOT NULL DEFAULT '',
    Summary TEXT NOT NULL DEFAULT '',
    Body TEXT NOT NULL DEFAULT '',
    Tags TEXT NOT NULL DEFAULT '',
    Score INTEGER NOT NULL DEFAULT 0,
    SortOrder INTEGER NOT NULL DEFAULT 100,
    PortalId INTEGER NULL,
    Source TEXT NOT NULL DEFAULT 'customer',
    Version INTEGER NOT NULL DEFAULT 1,
    CreatedByUserId INTEGER NULL,
    CreatedOnDate TEXT NOT NULL,
    UpdatedByUserId INTEGER NULL,
    UpdatedOnDate TEXT NULL
);
CREATE INDEX IF NOT EXISTS IX_MF_AI_KB_Templates_KnowledgeId ON MF_AI_KB_Templates(KnowledgeId);
CREATE UNIQUE INDEX IF NOT EXISTS IX_MF_AI_KB_Templates_Key ON MF_AI_KB_Templates(KnowledgeId, TemplateKey, PortalId);";
        }

        private static string CreateRulesSql(MegaFormDbContext db)
        {
            var p = (db.Database.ProviderName ?? string.Empty).ToLowerInvariant();
            if (p.Contains("sqlserver"))
                return @"
IF OBJECT_ID(N'[MF_AI_KB_Rules]', N'U') IS NULL
BEGIN
    CREATE TABLE [MF_AI_KB_Rules] (
        [RuleId] nvarchar(40) NOT NULL PRIMARY KEY,
        [KnowledgeId] int NULL,
        [WidgetType] nvarchar(60) NULL,
        [Title] nvarchar(200) NOT NULL DEFAULT '',
        [Severity] nvarchar(20) NOT NULL DEFAULT '',
        [Condition] nvarchar(max) NOT NULL DEFAULT '',
        [RegexPattern] nvarchar(500) NOT NULL DEFAULT '',
        [RejectionMessage] nvarchar(max) NOT NULL DEFAULT '',
        [FixHint] nvarchar(max) NOT NULL DEFAULT '',
        [Source] nvarchar(40) NOT NULL DEFAULT 'megaform-builtin',
        [Version] int NOT NULL DEFAULT 1,
        [Enabled] bit NOT NULL DEFAULT 1,
        [PortalId] int NULL,
        [CreatedByUserId] int NULL,
        [CreatedOnDate] datetime2 NOT NULL,
        [UpdatedByUserId] int NULL,
        [UpdatedOnDate] datetime2 NULL
    );
    CREATE INDEX [IX_MF_AI_KB_Rules_WidgetType] ON [MF_AI_KB_Rules]([WidgetType]);
    CREATE INDEX [IX_MF_AI_KB_Rules_KnowledgeId] ON [MF_AI_KB_Rules]([KnowledgeId]);
END";
            if (p.Contains("npgsql"))
                return @"
CREATE TABLE IF NOT EXISTS ""MF_AI_KB_Rules"" (
    ""RuleId"" text NOT NULL PRIMARY KEY,
    ""KnowledgeId"" integer NULL,
    ""WidgetType"" text NULL,
    ""Title"" text NOT NULL DEFAULT '',
    ""Severity"" text NOT NULL DEFAULT '',
    ""Condition"" text NOT NULL DEFAULT '',
    ""RegexPattern"" text NOT NULL DEFAULT '',
    ""RejectionMessage"" text NOT NULL DEFAULT '',
    ""FixHint"" text NOT NULL DEFAULT '',
    ""Source"" text NOT NULL DEFAULT 'megaform-builtin',
    ""Version"" integer NOT NULL DEFAULT 1,
    ""Enabled"" boolean NOT NULL DEFAULT true,
    ""PortalId"" integer NULL,
    ""CreatedByUserId"" integer NULL,
    ""CreatedOnDate"" timestamp without time zone NOT NULL,
    ""UpdatedByUserId"" integer NULL,
    ""UpdatedOnDate"" timestamp without time zone NULL
);
CREATE INDEX IF NOT EXISTS ""IX_MF_AI_KB_Rules_WidgetType"" ON ""MF_AI_KB_Rules""(""WidgetType"");
CREATE INDEX IF NOT EXISTS ""IX_MF_AI_KB_Rules_KnowledgeId"" ON ""MF_AI_KB_Rules""(""KnowledgeId"");";
            if (p.Contains("mysql"))
                return @"
CREATE TABLE IF NOT EXISTS `MF_AI_KB_Rules` (
    `RuleId` varchar(40) NOT NULL,
    `KnowledgeId` int NULL,
    `WidgetType` varchar(60) NULL,
    `Title` varchar(200) NOT NULL DEFAULT '',
    `Severity` varchar(20) NOT NULL DEFAULT '',
    `Condition` longtext NOT NULL,
    `RegexPattern` varchar(500) NOT NULL DEFAULT '',
    `RejectionMessage` longtext NOT NULL,
    `FixHint` longtext NOT NULL,
    `Source` varchar(40) NOT NULL DEFAULT 'megaform-builtin',
    `Version` int NOT NULL DEFAULT 1,
    `Enabled` tinyint(1) NOT NULL DEFAULT 1,
    `PortalId` int NULL,
    `CreatedByUserId` int NULL,
    `CreatedOnDate` datetime(6) NOT NULL,
    `UpdatedByUserId` int NULL,
    `UpdatedOnDate` datetime(6) NULL,
    PRIMARY KEY (`RuleId`),
    KEY `IX_MF_AI_KB_Rules_WidgetType` (`WidgetType`),
    KEY `IX_MF_AI_KB_Rules_KnowledgeId` (`KnowledgeId`)
);";
            return @"
CREATE TABLE IF NOT EXISTS MF_AI_KB_Rules (
    RuleId TEXT NOT NULL PRIMARY KEY,
    KnowledgeId INTEGER NULL,
    WidgetType TEXT NULL,
    Title TEXT NOT NULL DEFAULT '',
    Severity TEXT NOT NULL DEFAULT '',
    Condition TEXT NOT NULL DEFAULT '',
    RegexPattern TEXT NOT NULL DEFAULT '',
    RejectionMessage TEXT NOT NULL DEFAULT '',
    FixHint TEXT NOT NULL DEFAULT '',
    Source TEXT NOT NULL DEFAULT 'megaform-builtin',
    Version INTEGER NOT NULL DEFAULT 1,
    Enabled INTEGER NOT NULL DEFAULT 1,
    PortalId INTEGER NULL,
    CreatedByUserId INTEGER NULL,
    CreatedOnDate TEXT NOT NULL,
    UpdatedByUserId INTEGER NULL,
    UpdatedOnDate TEXT NULL
);
CREATE INDEX IF NOT EXISTS IX_MF_AI_KB_Rules_WidgetType ON MF_AI_KB_Rules(WidgetType);
CREATE INDEX IF NOT EXISTS IX_MF_AI_KB_Rules_KnowledgeId ON MF_AI_KB_Rules(KnowledgeId);";
        }

        private static string CreateFeedbackSql(MegaFormDbContext db)
        {
            var p = (db.Database.ProviderName ?? string.Empty).ToLowerInvariant();
            if (p.Contains("sqlserver"))
                return @"
IF OBJECT_ID(N'[MF_AI_KB_Feedback]', N'U') IS NULL
BEGIN
    CREATE TABLE [MF_AI_KB_Feedback] (
        [Id] bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [SessionId] nvarchar(80) NULL,
        [RuleId] nvarchar(40) NULL,
        [KnowledgeId] int NULL,
        [WidgetType] nvarchar(60) NULL,
        [Op] nvarchar(40) NULL,
        [AttemptedJson] nvarchar(max) NOT NULL DEFAULT '',
        [RejectionMessage] nvarchar(max) NULL,
        [FixedJson] nvarchar(max) NULL,
        [Outcome] nvarchar(20) NOT NULL DEFAULT 'rejected',
        [Promoted] bit NOT NULL DEFAULT 0,
        [PromotedTemplateId] int NULL,
        [PortalId] int NULL,
        [FormId] int NULL,
        [UserId] int NULL,
        [CreatedOnDate] datetime2 NOT NULL,
        [ReviewedByUserId] int NULL,
        [ReviewedOnDate] datetime2 NULL,
        [ReviewNotes] nvarchar(1000) NULL
    );
    CREATE INDEX [IX_MF_AI_KB_Feedback_Widget_Promoted] ON [MF_AI_KB_Feedback]([WidgetType], [Promoted], [CreatedOnDate]);
    CREATE INDEX [IX_MF_AI_KB_Feedback_Outcome] ON [MF_AI_KB_Feedback]([Outcome], [CreatedOnDate]);
    CREATE INDEX [IX_MF_AI_KB_Feedback_Rule] ON [MF_AI_KB_Feedback]([RuleId], [CreatedOnDate]);
END";
            if (p.Contains("npgsql"))
                return @"
CREATE TABLE IF NOT EXISTS ""MF_AI_KB_Feedback"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""SessionId"" text NULL,
    ""RuleId"" text NULL,
    ""KnowledgeId"" integer NULL,
    ""WidgetType"" text NULL,
    ""Op"" text NULL,
    ""AttemptedJson"" text NOT NULL DEFAULT '',
    ""RejectionMessage"" text NULL,
    ""FixedJson"" text NULL,
    ""Outcome"" text NOT NULL DEFAULT 'rejected',
    ""Promoted"" boolean NOT NULL DEFAULT false,
    ""PromotedTemplateId"" integer NULL,
    ""PortalId"" integer NULL,
    ""FormId"" integer NULL,
    ""UserId"" integer NULL,
    ""CreatedOnDate"" timestamp without time zone NOT NULL,
    ""ReviewedByUserId"" integer NULL,
    ""ReviewedOnDate"" timestamp without time zone NULL,
    ""ReviewNotes"" text NULL
);
CREATE INDEX IF NOT EXISTS ""IX_MF_AI_KB_Feedback_Widget_Promoted"" ON ""MF_AI_KB_Feedback""(""WidgetType"", ""Promoted"", ""CreatedOnDate"");
CREATE INDEX IF NOT EXISTS ""IX_MF_AI_KB_Feedback_Outcome"" ON ""MF_AI_KB_Feedback""(""Outcome"", ""CreatedOnDate"");
CREATE INDEX IF NOT EXISTS ""IX_MF_AI_KB_Feedback_Rule"" ON ""MF_AI_KB_Feedback""(""RuleId"", ""CreatedOnDate"");";
            if (p.Contains("mysql"))
                return @"
CREATE TABLE IF NOT EXISTS `MF_AI_KB_Feedback` (
    `Id` bigint NOT NULL AUTO_INCREMENT,
    `SessionId` varchar(80) NULL,
    `RuleId` varchar(40) NULL,
    `KnowledgeId` int NULL,
    `WidgetType` varchar(60) NULL,
    `Op` varchar(40) NULL,
    `AttemptedJson` longtext NOT NULL,
    `RejectionMessage` longtext NULL,
    `FixedJson` longtext NULL,
    `Outcome` varchar(20) NOT NULL DEFAULT 'rejected',
    `Promoted` tinyint(1) NOT NULL DEFAULT 0,
    `PromotedTemplateId` int NULL,
    `PortalId` int NULL,
    `FormId` int NULL,
    `UserId` int NULL,
    `CreatedOnDate` datetime(6) NOT NULL,
    `ReviewedByUserId` int NULL,
    `ReviewedOnDate` datetime(6) NULL,
    `ReviewNotes` varchar(1000) NULL,
    PRIMARY KEY (`Id`),
    KEY `IX_MF_AI_KB_Feedback_Widget_Promoted` (`WidgetType`, `Promoted`, `CreatedOnDate`),
    KEY `IX_MF_AI_KB_Feedback_Outcome` (`Outcome`, `CreatedOnDate`),
    KEY `IX_MF_AI_KB_Feedback_Rule` (`RuleId`, `CreatedOnDate`)
);";
            return @"
CREATE TABLE IF NOT EXISTS MF_AI_KB_Feedback (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    SessionId TEXT NULL,
    RuleId TEXT NULL,
    KnowledgeId INTEGER NULL,
    WidgetType TEXT NULL,
    Op TEXT NULL,
    AttemptedJson TEXT NOT NULL DEFAULT '',
    RejectionMessage TEXT NULL,
    FixedJson TEXT NULL,
    Outcome TEXT NOT NULL DEFAULT 'rejected',
    Promoted INTEGER NOT NULL DEFAULT 0,
    PromotedTemplateId INTEGER NULL,
    PortalId INTEGER NULL,
    FormId INTEGER NULL,
    UserId INTEGER NULL,
    CreatedOnDate TEXT NOT NULL,
    ReviewedByUserId INTEGER NULL,
    ReviewedOnDate TEXT NULL,
    ReviewNotes TEXT NULL
);
CREATE INDEX IF NOT EXISTS IX_MF_AI_KB_Feedback_Widget_Promoted ON MF_AI_KB_Feedback(WidgetType, Promoted, CreatedOnDate);
CREATE INDEX IF NOT EXISTS IX_MF_AI_KB_Feedback_Outcome ON MF_AI_KB_Feedback(Outcome, CreatedOnDate);
CREATE INDEX IF NOT EXISTS IX_MF_AI_KB_Feedback_Rule ON MF_AI_KB_Feedback(RuleId, CreatedOnDate);";
        }
    }
}
