using System;
using Microsoft.EntityFrameworkCore;

namespace MegaForm.Web.Data
{
    public static class ReportsSchemaBootstrapper
    {
        public static void EnsureReportTables(MegaFormDbContext db)
        {
            EnsureTable(db, "MF_ReportDefinitions", CreateReportDefinitionsSql(db));
        }

        private static void EnsureTable(MegaFormDbContext db, string tableName, string createSql)
        {
            if (string.IsNullOrWhiteSpace(createSql)) return;
            if (TableExists(db, tableName)) return;
            ExecuteNonQuery(db, createSql);
        }

        private static bool TableExists(MegaFormDbContext db, string tableName)
        {
            var provider = (db.Database.ProviderName ?? string.Empty).ToLowerInvariant();
            var conn = db.Database.GetDbConnection();
            var shouldClose = conn.State != System.Data.ConnectionState.Open;
            if (shouldClose) conn.Open();
            try
            {
                using var cmd = conn.CreateCommand();
                cmd.CommandText = provider.Contains("sqlserver")
                    ? "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE LOWER(TABLE_NAME) = LOWER(@tableName)"
                    : provider.Contains("npgsql")
                        ? "SELECT COUNT(*) FROM information_schema.tables WHERE LOWER(table_name) = LOWER(@tableName)"
                        : provider.Contains("mysql")
                            ? "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = DATABASE() AND LOWER(table_name) = LOWER(@tableName)"
                            : "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND LOWER(name) = LOWER(@tableName)";
                var p = cmd.CreateParameter(); p.ParameterName = "@tableName"; p.Value = tableName; cmd.Parameters.Add(p);
                return Convert.ToInt32(cmd.ExecuteScalar() ?? 0) > 0;
            }
            finally { if (shouldClose) conn.Close(); }
        }

        private static void ExecuteNonQuery(MegaFormDbContext db, string sql)
        {
            var conn = db.Database.GetDbConnection();
            var shouldClose = conn.State != System.Data.ConnectionState.Open;
            if (shouldClose) conn.Open();
            try { using var cmd = conn.CreateCommand(); cmd.CommandText = sql; cmd.ExecuteNonQuery(); }
            finally { if (shouldClose) conn.Close(); }
        }

        private static string CreateReportDefinitionsSql(MegaFormDbContext db)
        {
            var p = (db.Database.ProviderName ?? string.Empty).ToLowerInvariant();
            if (p.Contains("sqlserver"))
                return @"
IF OBJECT_ID(N'[MF_ReportDefinitions]', N'U') IS NULL
BEGIN
    CREATE TABLE [MF_ReportDefinitions] (
        [ReportId] int IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [PortalId] int NOT NULL DEFAULT 0,
        [Name] nvarchar(200) NOT NULL DEFAULT '',
        [AppScope] nvarchar(100) NOT NULL DEFAULT '',
        [DefinitionJson] nvarchar(max) NOT NULL DEFAULT '{}',
        [CreatedByUserId] int NULL,
        [CreatedOnUtc] datetime2 NOT NULL,
        [UpdatedOnUtc] datetime2 NULL
    );
    CREATE INDEX [IX_MF_ReportDefinitions_Portal_AppScope] ON [MF_ReportDefinitions]([PortalId], [AppScope]);
END";
            if (p.Contains("npgsql"))
                return @"
CREATE TABLE IF NOT EXISTS ""MF_ReportDefinitions"" (
    ""ReportId"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""PortalId"" integer NOT NULL DEFAULT 0,
    ""Name"" text NOT NULL DEFAULT '',
    ""AppScope"" text NOT NULL DEFAULT '',
    ""DefinitionJson"" text NOT NULL DEFAULT '{}',
    ""CreatedByUserId"" integer NULL,
    ""CreatedOnUtc"" timestamp without time zone NOT NULL,
    ""UpdatedOnUtc"" timestamp without time zone NULL
);
CREATE INDEX IF NOT EXISTS ""IX_MF_ReportDefinitions_Portal_AppScope"" ON ""MF_ReportDefinitions""(""PortalId"", ""AppScope"");";
            if (p.Contains("mysql"))
                return @"
CREATE TABLE IF NOT EXISTS `MF_ReportDefinitions` (
    `ReportId` int NOT NULL AUTO_INCREMENT,
    `PortalId` int NOT NULL DEFAULT 0,
    `Name` varchar(200) NOT NULL DEFAULT '',
    `AppScope` varchar(100) NOT NULL DEFAULT '',
    `DefinitionJson` longtext NOT NULL,
    `CreatedByUserId` int NULL,
    `CreatedOnUtc` datetime(6) NOT NULL,
    `UpdatedOnUtc` datetime(6) NULL,
    PRIMARY KEY (`ReportId`),
    KEY `IX_MF_ReportDefinitions_Portal_AppScope` (`PortalId`, `AppScope`)
);";
            return @"
CREATE TABLE IF NOT EXISTS MF_ReportDefinitions (
    ReportId INTEGER PRIMARY KEY AUTOINCREMENT,
    PortalId INTEGER NOT NULL DEFAULT 0,
    Name TEXT NOT NULL DEFAULT '',
    AppScope TEXT NOT NULL DEFAULT '',
    DefinitionJson TEXT NOT NULL DEFAULT '{}',
    CreatedByUserId INTEGER NULL,
    CreatedOnUtc TEXT NOT NULL,
    UpdatedOnUtc TEXT NULL
);
CREATE INDEX IF NOT EXISTS IX_MF_ReportDefinitions_Portal_AppScope ON MF_ReportDefinitions(PortalId, AppScope);";
        }
    }
}
